import type { PermissionDecision } from './permissions'; import type { QueryEnvelope } from './query'; import type { FilterGroup } from './filters';
export type ReceiptStatus='submitted'|'accepted'|'queued'|'approved'|'executing'|'partial'|'completed'|'failed'|'rolled_back';
export type AuditEvent={id:string;actor:string;action:string;target:{type:string;id:string};scope:string[];before?:unknown;after?:unknown;reason:string;requestId:string;policyDecisionId:string;timestamp:string;revision?:number;receiptRef?:string;approvalChain:string[];externalReferences:string[]};
export type Receipt={receiptId:string;requestId:string;actionId:string;actor:string;target:{type:string;id:string};submittedAt:string;acceptedAt?:string;queuedAt?:string;completedAt?:string;externalReferences:string[];status:ReceiptStatus;partialSuccess:boolean;failureItems:{id:string;reason:string}[];retryable:boolean;rollbackAvailable:boolean;auditLink:string;rehydration:'pending'|'authoritative'|'failed';prototypeSimulation:boolean};
export type ActionContract<T>={actionId:string;label:string;target:{type:string;id:string};targetScope:string[];capability:string;preconditions:string[];inputSchema:string;validate(input:T):{valid:boolean;errors:string[]};impactPreview(input:T):unknown;confirmation:string;approvalRequirement:'none'|'required';idempotencyKey:string;expectedRevision?:number;retryable:boolean;rollbackAvailable:boolean};
export type ExportRequest={classification:'internal'|'confidential'|'restricted';fields:string[];filters:FilterGroup;query:QueryEnvelope;timeRange:QueryEnvelope['timeRange'];rowCountEstimate?:number;permissionDecision:PermissionDecision;redactions:string[]};
export type ExportJob={jobId:string;request:ExportRequest;status:ReceiptStatus;progress:number;expiresAt?:string;receipt:Receipt;audit:AuditEvent;failureReason?:string};
export interface ExportJobService{create(request:ExportRequest,actor:string):Promise<ExportJob>;get(jobId:string):Promise<ExportJob>}
export class PrototypeExportJobService implements ExportJobService{private jobs=new Map<string,ExportJob>();async create(request:ExportRequest,actor:string){if(!request.permissionDecision.allowed)throw new Error(`EXPORT_DENIED: ${request.permissionDecision.reason}`);const requestId=`req-${crypto.randomUUID()}`;const jobId=`export-${crypto.randomUUID()}`;const now=new Date().toISOString();const receipt:Receipt={receiptId:`receipt-${crypto.randomUUID()}`,requestId,actionId:'events.export',actor,target:{type:'query',id:request.query.raw||'all'},submittedAt:now,acceptedAt:now,queuedAt:now,externalReferences:[],status:'queued',partialSuccess:false,failureItems:[],retryable:true,rollbackAvailable:false,auditLink:`audit/${requestId}`,rehydration:'pending',prototypeSimulation:true};const audit:AuditEvent={id:`audit-${crypto.randomUUID()}`,actor,action:'events.export',target:{type:'query',id:request.query.raw||'all'},scope:request.permissionDecision.audit.scope,reason:'Prototype export review',requestId,policyDecisionId:request.permissionDecision.decisionId,timestamp:now,receiptRef:receipt.receiptId,approvalChain:[],externalReferences:[]};const job={jobId,request,status:'queued' as const,progress:0,receipt,audit};this.jobs.set(jobId,job);return structuredClone(job);}async get(id:string){const j=this.jobs.get(id);if(!j)throw new Error('EXPORT_NOT_FOUND');return structuredClone(j);}}
export const createIdempotencyKey=(actionId:string,targetId:string,revision?:number)=>`${actionId}:${targetId}:${revision??'none'}:${crypto.randomUUID()}`;
export function assertExpectedRevision(expected:number|undefined,actual:number){if(expected!==undefined&&expected!==actual)throw new Error('REVISION_CONFLICT');}
export const isCompleted=(r:Receipt)=>r.status==='completed';
