import type { CompareOp } from './query';
export type FilterValue=string|number|boolean|string[]; export type FilterCondition={id:string;kind:'condition';field:string;operator:CompareOp;value:FilterValue;valueType:'string'|'number'|'boolean'|'date'|'list';exclude:boolean;label:string;disabledReason?:string}; export type FilterGroup={id:string;kind:'group';operator:'AND'|'OR';children:(FilterCondition|FilterGroup)[]};
export type FilterField={name:string;label:string;type:FilterCondition['valueType'];operators:CompareOp[];visible:boolean;dependsOn?:string};
export type FacetResult={field:string;values:{value:string;count?:number}[];status:'ready'|'stale'|'partial'|'error'};
export const emptyFilters=():FilterGroup=>({id:'root',kind:'group',operator:'AND',children:[]});
export const addCondition=(g:FilterGroup,c:FilterCondition):FilterGroup=>({...g,children:[...g.children,c]});
export const removeFilter=(g:FilterGroup,id:string):FilterGroup=>({...g,children:g.children.filter(c=>c.id!==id).map(c=>c.kind==='group'?removeFilter(c,id):c)});
export const updateCondition=(g:FilterGroup,id:string,patch:Partial<FilterCondition>):FilterGroup=>({...g,children:g.children.map(c=>c.kind==='group'?updateCondition(c,id,patch):c.id===id?{...c,...patch}:c)});
export function normalizeFlatFilters(cs:FilterCondition[]):FilterGroup{const by=new Map<string,FilterCondition[]>();cs.forEach(c=>by.set(c.field,[...(by.get(c.field)??[]),c]));return{id:'root',kind:'group',operator:'AND',children:[...by.entries()].map(([field,items])=>items.length===1?items[0]:{id:`group-${field}`,kind:'group',operator:'OR',children:items})};}
export const serializeFilters=(f:FilterGroup)=>encodeURIComponent(JSON.stringify(f)); export const deserializeFilters=(s:string)=>JSON.parse(decodeURIComponent(s)) as FilterGroup;
export function applyFieldPermissions(group:FilterGroup,fields:FilterField[]):{filters:FilterGroup;warnings:string[]}{const visible=new Set(fields.filter(f=>f.visible).map(f=>f.name));const warnings:string[]=[];const walk=(g:FilterGroup):FilterGroup=>{const children:(FilterCondition|FilterGroup)[]=[];for(const c of g.children){if(c.kind==='group')children.push(walk(c));else if(!visible.has(c.field))warnings.push(`Removed inaccessible field: ${c.field}`);else children.push(c);}return{...g,children};};return{filters:walk(group),warnings};}
export function dependencyReason(field:FilterField,group:FilterGroup){if(!field.dependsOn)return undefined;const has=(g:FilterGroup):boolean=>g.children.some(c=>c.kind==='group'?has(c):c.field===field.dependsOn);return has(group)?undefined:`Select ${field.dependsOn} first.`;}
