export type BooleanOp='AND'|'OR'; export type CompareOp=':'|'='|'!='|'>'|'>='|'<'|'<='|'PREFIX';
export type Span={start:number;end:number};
export type QueryNode=
 | {kind:'term';value:string;quoted:boolean;span:Span}
 | {kind:'condition';field:string;operator:CompareOp;value:string;span:Span}
 | {kind:'not';child:QueryNode;span:Span}
 | {kind:'group';operator:BooleanOp;children:QueryNode[];span:Span};
export type QueryError={code:'SYNTAX'|'INVALID_FIELD'|'INVALID_OPERATOR'|'PERMISSION_DENIED'|'INVALID_TIME';token:string;field?:string;operator?:string;message:string;recoverHint:string;span:Span};
export type FieldDefinition={name:string;operators:readonly CompareOp[];visible:boolean;type:'string'|'keyword'|'date'|'number'};
export type QueryEnvelope={schemaVersion:1;raw:string;ast:QueryNode|null;timeRange:{field:'event_time'|'ingested_at';from:string;to:string;timezone:string};sort:{field:string;direction:'asc'|'desc'}[];cursor?:string;limit:number;projection:string[];aggregations:{id:string;type:'date_histogram'|'terms';field:string}[]};

type Token={value:string;span:Span;quoted:boolean};
export function tokenize(raw:string):Token[]{const out:Token[]=[]; let i=0; while(i<raw.length){if(/\s/.test(raw[i])){i++;continue;} const start=i; if(raw[i]==='"'){i++;let v='';while(i<raw.length&&raw[i]!=='"')v+=raw[i++];if(raw[i]==='"')i++;out.push({value:v,span:{start,end:i},quoted:true});continue;} if('()'.includes(raw[i])){out.push({value:raw[i],span:{start,end:++i},quoted:false});continue;} let v='';while(i<raw.length&&!/\s|\(|\)/.test(raw[i]))v+=raw[i++];out.push({value:v,span:{start,end:i},quoted:false});} return out;}
function conditionFrom(token:Token):QueryNode{const m=token.value.match(/^([\w.]+)(:|>=|<=|!=|=|>|<)(.+)$/); if(m)return{kind:'condition',field:m[1],operator:m[2] as CompareOp,value:m[3],span:token.span}; return{kind:'term',value:token.value,quoted:token.quoted,span:token.span};}
export function parseQuery(raw:string):{ast:QueryNode|null;errors:QueryError[]}{const ts=tokenize(raw);let p=0;const errors:QueryError[]=[];const parsePrimary=():QueryNode|null=>{const t=ts[p];if(!t)return null;if(t.value==='NOT'){p++;const child=parsePrimary();return child?{kind:'not',child,span:{start:t.span.start,end:child.span.end}}:null;}if(t.value==='('){p++;const inner=parseExpr();const close=ts[p];if(!close||close.value!==')'){errors.push({code:'SYNTAX',token:'(',message:'Unclosed group',recoverHint:'Add a closing parenthesis.',span:t.span});return inner;}p++;return inner?{kind:'group',operator:'AND',children:[inner],span:{start:t.span.start,end:close.span.end}}:null;}p++;return conditionFrom(t);};const parseExpr=():QueryNode|null=>{let left=parsePrimary();while(p<ts.length&&ts[p].value!==')'){const op=(ts[p].value==='AND'||ts[p].value==='OR')?ts[p++].value as BooleanOp:'AND';const right=parsePrimary();if(!right)break;if(!left)left=right;else if(left.kind==='group'&&left.operator===op)left={...left,children:[...left.children,right],span:{start:left.span.start,end:right.span.end}};else left={kind:'group',operator:op,children:[left,right],span:{start:left.span.start,end:right.span.end}};}return left;};return{ast:parseExpr(),errors};}
export function validateQuery(ast:QueryNode|null,catalog:FieldDefinition[],range:QueryEnvelope['timeRange']):QueryError[]{const errors:QueryError[]=[];const map=new Map(catalog.map(f=>[f.name,f]));const walk=(n:QueryNode)=>{if(n.kind==='condition'){const f=map.get(n.field);if(!f)errors.push({code:'INVALID_FIELD',token:n.field,field:n.field,operator:n.operator,message:`Unsupported field ${n.field}`,recoverHint:'Choose a field from the field catalog.',span:n.span});else if(!f.visible)errors.push({code:'PERMISSION_DENIED',token:n.field,field:n.field,operator:n.operator,message:`Field ${n.field} is not visible`,recoverHint:'Remove the field or request access.',span:n.span});else if(!f.operators.includes(n.operator))errors.push({code:'INVALID_OPERATOR',token:n.operator,field:n.field,operator:n.operator,message:`Operator ${n.operator} is not valid for ${n.field}`,recoverHint:`Use one of: ${f.operators.join(', ')}`,span:n.span});}else if(n.kind==='group')n.children.forEach(walk);else if(n.kind==='not')walk(n.child);};if(ast)walk(ast);if(Date.parse(range.from)>=Date.parse(range.to))errors.push({code:'INVALID_TIME',token:`${range.from}..${range.to}`,field:range.field,message:'Time range start must precede end',recoverHint:'Choose an earlier start or later end.',span:{start:0,end:0}});return errors;}
export function createEnvelope(raw:string,overrides:Partial<QueryEnvelope>={}):QueryEnvelope{const {ast}=parseQuery(raw);return{schemaVersion:1,raw,ast,timeRange:{field:'event_time',from:'2026-07-17T00:00:00Z',to:'2026-07-18T00:00:00Z',timezone:'Asia/Taipei'},sort:[{field:'event_time',direction:'desc'}],limit:25,projection:['event_time','severity','source','host','user','action'],aggregations:[{id:'timeline',type:'date_histogram',field:'event_time'}],...overrides};}
export const serializeQuery=(q:QueryEnvelope)=>btoa(unescape(encodeURIComponent(JSON.stringify(q))));
export const deserializeQuery=(s:string)=>JSON.parse(decodeURIComponent(escape(atob(s)))) as QueryEnvelope;
