import { EuiBadge, EuiButtonEmpty, EuiSwitch, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture } from '../../types/prototype';

export function ItsmConfigurationStudio({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="itsmConfigurationStudio" data-visual-region="itsm-configuration-studio">
    <aside className="itsmResourceNavigator" data-visual-region="itsm-resource-navigator"><EuiTitle size="xs"><h2>ITSM resources</h2></EuiTitle>{['SLA definitions','Priority matrix','Assignment rules','State models','Field mappings'].map((item,index)=><button type="button" key={item} className={index===0?'selected':''}><strong>{item}</strong><small>{index===0?'revision 12':'configured'}</small></button>)}</aside>
    <section className="slaDefinitionCanvas" data-visual-region="sla-definition-canvas"><header><div><EuiBadge color="warning">Draft revision 13</EuiBadge><h2>Critical incident response SLA</h2></div><EuiButtonEmpty>Compare revision</EuiButtonEmpty></header><div className="slaDefinitionGrid"><label><span>Start condition</span><button type="button">Incident state = Open</button></label><label><span>Target</span><button type="button">15 business minutes</button></label><label><span>Calendar</span><button type="button">24×7 critical support</button></label><label><span>Stop condition</span><button type="button">State = Resolved</button></label></div><div className="slaPauseLogic"><strong>Pause logic</strong>{['Waiting for customer','Awaiting vendor','Planned maintenance'].map((item,index)=><label key={item}><input type="checkbox" defaultChecked={index<2}/>{item}</label>)}</div></section>
    <aside className="configurationDependencyRail" data-visual-region="configuration-dependency-rail"><EuiTitle size="xs"><h2>Dependencies</h2></EuiTitle>{['Incident state model','Business calendar','Priority policy','Notification workflow'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index===2?'warning':'success'}>{index===2?'Draft':'Current'}</EuiBadge></div>)}</aside>
    <section className="slaImpactSimulation" data-visual-region="sla-impact-simulation"><EuiTitle size="xs"><h2>Impact simulation</h2></EuiTitle><div className="simulationMetrics"><article><b>23</b><span>current breaches</span></article><article><b>17</b><span>after change</span></article><article><b>6</b><span>reclassified</span></article></div><p>Fixture replay against {fixture.rows.length} sample incidents; no production SLA is changed.</p></section>
    <section className="configurationChangeLedger" data-visual-region="configuration-change-ledger"><EuiTitle size="xs"><h2>Change ledger</h2></EuiTitle>{fixture.timeline.slice(0,4).map((item,index)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><span>revision {12-index}</span><EuiBadge color={index===0?'warning':'hollow'}>{index===0?'Draft':'Published'}</EuiBadge></div>)}</section>
  </div>;
}

export function PlatformSettingsDirectory({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="platformSettingsDirectory" data-visual-region="platform-settings-directory">
    <section className="settingsDirectoryHero" data-visual-region="settings-directory-hero"><div><EuiBadge color="primary">Configuration directory</EuiBadge><h2>Platform settings ownership</h2><p>Navigate by domain, understand source-of-truth ownership and preview change blast radius.</p></div><div className="settingsSearch"><input aria-label="Search platform settings" placeholder="Search settings, owner or capability"/><EuiBadge color="hollow">42 groups</EuiBadge></div></section>
    <section className="settingsDomainMap" data-visual-region="settings-domain-map"><EuiTitle size="xs"><h2>Settings domains</h2></EuiTitle>{['Security analytics','ITSM','Identity','Data & ingest','Agents','Appearance'].map((domain,index)=><article key={domain}><span className={`domainGlyph domain-${index}`}>{domain.slice(0,2)}</span><div><strong>{domain}</strong><small>{5+index} setting groups · {index%3} drafts</small></div><EuiButtonEmpty size="xs">Open</EuiButtonEmpty></article>)}</section>
    <aside className="settingsOwnerDirectory" data-visual-region="settings-owner-directory"><EuiTitle size="xs"><h2>Ownership directory</h2></EuiTitle>{['Platform SRE','Security engineering','ITSM governance','Identity operations'].map((team,index)=><div key={team}><span className="ownerAvatar">{team.slice(0,2)}</span><div><strong>{team}</strong><small>{8-index} groups · review {index+1}d</small></div></div>)}</aside>
    <section className="settingsChangeImpactMap" data-visual-region="settings-change-impact-map"><EuiTitle size="xs"><h2>Pending change impact</h2></EuiTitle>{fixture.rows.slice(0,5).map((row,index)=><div key={row.id}><strong>{row.id}</strong><span>{['Identity rollout','SLA policy','Ingest mapping','Theme tokens','Agent policy'][index]}</span><EuiBadge color={index<2?'warning':'hollow'}>{index<2?'Cross-domain':'Local'}</EuiBadge></div>)}</section>
  </div>;
}

export function IdentityProviderTopology({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="identityProviderTopology" data-visual-region="identity-provider-topology">
    <section className="providerTopologyCanvas" data-visual-region="provider-topology-canvas"><header><div><EuiBadge color="primary">Authentication topology</EuiBadge><h2>Provider routing and fallback</h2></div><strong>3 providers</strong></header><div className="providerGraph"><span className="authEntry">SOC users</span><span className="providerNode oidc">OIDC<small>Primary</small></span><span className="providerNode ldap">LDAP<small>Fallback</small></span><span className="providerNode local">Local<small>Break glass</small></span><span className="authApps">SOC / ITSM apps</span></div></section>
    <aside className="authenticationTestConsole" data-visual-region="authentication-test-console"><EuiTitle size="xs"><h2>Connection test</h2></EuiTitle><dl><div><dt>DNS</dt><dd>12 ms</dd></div><div><dt>TLS</dt><dd>Valid</dd></div><div><dt>Bind</dt><dd>Success</dd></div><div><dt>Claims</dt><dd>2 warnings</dd></div></dl><EuiButtonEmpty>Run test</EuiButtonEmpty><EuiBadge color="warning">No secret values exposed</EuiBadge></aside>
    <section className="providerConfigurationForm" data-visual-region="provider-configuration-form"><EuiTitle size="xs"><h2>OIDC provider configuration</h2></EuiTitle><div className="providerFormGrid"><label>Issuer<input defaultValue="https://identity.example.test" /></label><label>Client ID<input defaultValue="soc-platform" /></label><label>Client secret<input type="password" defaultValue="masked-secret" /></label><label>Fallback<input defaultValue="LDAP / local break-glass" /></label></div><div className="providerRollout"><strong>Rollout</strong>{['Pilot administrators','SOC analysts','All users'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index===0?'success':index===1?'warning':'hollow'}>{index===0?'Complete':index===1?'Next':'Blocked'}</EuiBadge></div>)}</div></section>
    <section className="authenticationAuditLedger" data-visual-region="authentication-audit-ledger"><EuiTitle size="xs"><h2>Authentication audit</h2></EuiTitle>{fixture.timeline.slice(0,5).map((item,index)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><span>actor admin-{index+1}</span><EuiBadge color="hollow">receipt</EuiBadge></div>)}</section>
  </div>;
}

export function ThemeAccessibilityStudio() {
  return <div className="themeAccessibilityStudio" data-visual-region="theme-accessibility-studio">
    <aside className="tokenWorkbench" data-visual-region="token-workbench"><EuiTitle size="xs"><h2>Token workbench</h2></EuiTitle>{['Semantic color','Typography','Spacing','Radius','Focus','Motion'].map((group,index)=><button type="button" key={group} className={index===0?'selected':''}><strong>{group}</strong><small>{4+index} tokens</small></button>)}</aside>
    <section className="contrastMatrix" data-visual-region="contrast-matrix"><header><div><EuiBadge color="primary">Accessibility lab</EuiBadge><h2>Contrast matrix</h2></div><strong>18 / 20 pass</strong></header><div className="contrastCards">{['Text / canvas','Muted / canvas','Danger / canvas','Focus / canvas','Badge / panel','Link / panel'].map((item,index)=><article key={item} className={index===1?'contrastWarn':''}><span className="contrastSwatch"/><div><strong>{item}</strong><small>{index===1?'3.8:1':'7.1:1'}</small></div><EuiBadge color={index===1?'warning':'success'}>{index===1?'Review':'Pass'}</EuiBadge></article>)}</div></section>
    <section className="interactionAccessibilityLab" data-visual-region="interaction-accessibility-lab"><EuiTitle size="xs"><h2>Interaction accessibility</h2></EuiTitle>{['Visible keyboard focus','Reduced motion','Non-color status labels','Focus restore','Accessible names'].map((item,index)=><div key={item}><EuiSwitch label={item} checked={index!==3} onChange={()=>undefined}/><EuiBadge color={index===3?'warning':'success'}>{index===3?'Test':'Pass'}</EuiBadge></div>)}</section>
    <section className="zoomResponsiveLab" data-visual-region="zoom-responsive-lab"><EuiTitle size="xs"><h2>Zoom & responsive lab</h2></EuiTitle><div className="zoomPreview"><aside/><main><header/><section/><section/></main></div><footer><EuiBadge color="success">200% no root overflow</EuiBadge><EuiBadge color="hollow">D1080 / D2K / D4K</EuiBadge></footer></section>
  </div>;
}
