import { EuiBadge, EuiButtonEmpty, EuiProgress, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow } from '../../types/prototype';

const rowText = (row: PrototypeRow, field: string, fallback: string) => String(row[field] ?? fallback);

export function CaseInvestigationWorkbench({ fixture }: { fixture: PrototypePageFixture }) {
  const cases = fixture.rows.slice(0, 7);
  return <div className="caseInvestigationWorkbench" data-visual-region="case-investigation-workbench">
    <aside className="casePriorityRail" data-visual-region="case-priority-rail"><EuiTitle size="xs"><h2>Investigation priority</h2></EuiTitle>{cases.slice(0,5).map((row,index)=><button type="button" key={row.id} className={index===0?'selected':''}><b>{index+1}</b><span>{row.id}</span><small>{row.severity} · {row.owner}</small></button>)}</aside>
    <section className="caseEvidenceCanvas" data-visual-region="case-evidence-canvas"><header><div><EuiBadge color="danger">High confidence</EuiBadge><h2>{rowText(cases[0],'title','Credential access investigation')}</h2><p>{cases[0].id} · owner {cases[0].owner}</p></div><EuiButtonEmpty>Open full case</EuiButtonEmpty></header><div className="evidenceLanes"><article><strong>Evidence</strong><b>18</b><span>3 gaps</span></article><article><strong>Entities</strong><b>7</b><span>2 high risk</span></article><article><strong>Tasks</strong><b>5</b><span>1 overdue</span></article></div><div className="evidenceGraph">{['Alert','Identity','Host','IP','Process','Case'].map((item,index)=><span key={item} style={{left:`${12+(index%3)*38}%`,top:`${22+Math.floor(index/3)*52}%`}}>{item}</span>)}</div></section>
    <aside className="caseDecisionRail" data-visual-region="case-decision-rail"><EuiTitle size="xs"><h2>Next decision</h2></EuiTitle><ol><li><strong>Validate identity pivot</strong><small>2 conflicting source values</small></li><li><strong>Request endpoint capture</strong><small>Capability eligible</small></li><li><strong>Prepare containment</strong><small>Approval required</small></li></ol></aside>
    <section className="caseReadinessMap" data-visual-region="evidence-readiness-map"><EuiTitle size="xs"><h2>Evidence readiness</h2></EuiTitle>{['Identity','Endpoint','Network','Cloud'].map((item,index)=><div key={item}><span>{item}</span><EuiProgress value={94-index*13} max={100} size="s" color={index===2?'warning':'primary'} /><small>{94-index*13}%</small></div>)}</section>
    <section className="caseHypothesis" data-visual-region="case-hypothesis"><EuiTitle size="xs"><h2>Working hypothesis</h2></EuiTitle><p>Credential misuse followed by privileged access from a newly observed host.</p><div><EuiBadge color="warning">Confidence 78%</EuiBadge><EuiBadge color="hollow">2 alternatives</EuiBadge></div></section>
    <section className="caseActivityRibbon" data-visual-region="case-activity-ribbon">{fixture.timeline.slice(0,5).map((item)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><small>{item.status}</small></div>)}</section>
  </div>;
}

export function IncidentCommandBoard({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="incidentCommandBoard" data-visual-region="incident-command-board">
    <section className="incidentPriorityDeck" data-visual-region="incident-priority-deck"><header><div><EuiBadge color="danger">P1 service impact</EuiBadge><h2>Incident priority deck</h2></div><strong>00:24:18</strong></header>{fixture.rows.slice(0,5).map((row,index)=><article key={row.id}><span className={`priorityPill p${index+1}`}>P{Math.min(index+1,4)}</span><div><strong>{rowText(row,'summary',row.id)}</strong><small>{rowText(row,'service_ref','Identity service')} · {row.owner}</small></div><div><b>{18+index*7}m</b><small>SLA left</small></div></article>)}</section>
    <aside className="incidentSlaComms" data-visual-region="incident-sla-comms"><EuiTitle size="xs"><h2>SLA & communications</h2></EuiTitle><div className="slaDial"><strong>24m</strong><span>to response breach</span></div><ol><li>Stakeholder update due 12:30</li><li>Vendor bridge active</li><li>Major incident review pending</li></ol></aside>
    <section className="serviceImpactCanvas" data-visual-region="service-impact-canvas"><EuiTitle size="xs"><h2>Service impact</h2></EuiTitle><div className="impactTopology"><span className="impactCore">Identity API</span>{['VPN','Admin portal','HR apps','Cloud login'].map((item,index)=><span key={item} className={`impactNode node-${index}`}>{item}<small>{index<2?'Degraded':'At risk'}</small></span>)}</div></section>
    <section className="restorationRunbook" data-visual-region="restoration-runbook"><EuiTitle size="xs"><h2>Restoration runbook</h2></EuiTitle>{['Confirm blast radius','Fail over provider','Validate authentication','Restore normal routing'].map((item,index)=><div key={item}><b>{index+1}</b><span>{item}</span><EuiBadge color={index<2?'success':index===2?'warning':'hollow'}>{index<2?'Done':index===2?'Running':'Pending'}</EuiBadge></div>)}</section>
    <footer className="incidentHandoffLane" data-visual-region="incident-handoff-lane"><strong>Shift handoff</strong><span>Service owner acknowledged · next update 12:30 UTC · resolution receipt not yet authoritative.</span></footer>
  </div>;
}

export function ProblemKnowledgeWorkbench({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="problemKnowledgeWorkbench" data-visual-region="problem-knowledge-workbench">
    <section className="problemHypothesisBoard" data-visual-region="problem-hypothesis-board"><header><div><EuiBadge color="warning">Root cause analysis</EuiBadge><h2>Hypothesis board</h2></div><strong>3 active</strong></header>{['Token cache race','Provider timeout cascade','Configuration drift'].map((item,index)=><article key={item}><div className="hypothesisScore"><b>{82-index*17}%</b><small>confidence</small></div><div><strong>{item}</strong><p>{2+index} supporting signals · {index} contradictions</p></div><EuiBadge color={index===0?'warning':'hollow'}>{index===0?'Leading':'Candidate'}</EuiBadge></article>)}</section>
    <aside className="recurrenceFingerprint" data-visual-region="recurrence-fingerprint"><EuiTitle size="xs"><h2>Recurrence fingerprint</h2></EuiTitle><div className="fingerprintBars">{fixture.chart.slice(0,10).map((point)=><i key={point.label} style={{height:`${point.value}%`}} />)}</div><p>Pattern repeated across 4 incidents in 21 days.</p></aside>
    <section className="workaroundRegistry" data-visual-region="workaround-registry"><EuiTitle size="xs"><h2>Known workarounds</h2></EuiTitle>{['Flush token cache','Pin provider pool','Disable eager refresh'].map((item,index)=><div key={item}><strong>{item}</strong><span>{index===0?'Validated':'Draft'}</span><EuiBadge color={index===0?'success':'warning'}>{index===0?'Safe':'Review'}</EuiBadge></div>)}</section>
    <section className="problemEvidenceLedger" data-visual-region="problem-evidence-ledger"><EuiTitle size="xs"><h2>Evidence ledger</h2></EuiTitle><table><thead><tr><th>Evidence</th><th>Supports</th><th>Revision</th></tr></thead><tbody>{fixture.rows.slice(0,5).map((row,index)=><tr key={row.id}><td>{row.id}</td><td>{['Token cache race','Provider timeout cascade','Configuration drift'][index%3]}</td><td>r{7-index}</td></tr>)}</tbody></table></section>
  </div>;
}

export function ChangeControlWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="changeControlWorkspace" data-visual-region="change-control-workspace">
    <section className="changeCalendarCanvas" data-visual-region="change-calendar-canvas"><header><div><EuiBadge color="primary">Change window</EuiBadge><h2>Implementation calendar</h2></div><strong>7-day horizon</strong></header><div className="changeCalendarRows">{['Identity','Network','Endpoint','Cloud'].map((lane,laneIndex)=><div key={lane}><b>{lane}</b><span className="windowBlock" style={{left:`${8+laneIndex*11}%`,width:`${22+laneIndex*4}%`}}>{lane} rollout</span><span className="incidentBlock" style={{left:`${58-laneIndex*4}%`,width:'15%'}}>Incident</span></div>)}</div></section>
    <aside className="cabDecisionLane" data-visual-region="cab-decision-lane"><EuiTitle size="xs"><h2>CAB decisions</h2></EuiTitle>{fixture.rows.slice(0,4).map((row,index)=><article key={row.id}><strong>{row.id}</strong><small>{rowText(row,'summary','Change request')}</small><EuiBadge color={index===0?'danger':index===1?'warning':'success'}>{index===0?'Blocked':index===1?'Needs evidence':'Approved'}</EuiBadge></article>)}</aside>
    <section className="changeCollisionMatrix" data-visual-region="change-collision-matrix"><EuiTitle size="xs"><h2>Collision matrix</h2></EuiTitle><div className="collisionGrid">{Array.from({length:16},(_,index)=><span key={index} className={index===5||index===10?'collisionHigh':index%3===0?'collisionWarn':''}>{index===5||index===10?'High':index%3===0?'Med':'Low'}</span>)}</div></section>
    <section className="rollbackReadiness" data-visual-region="rollback-readiness"><EuiTitle size="xs"><h2>Rollback readiness</h2></EuiTitle>{['Snapshot verified','Owner available','Backout script tested','Monitoring ready'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index<3?'success':'warning'}>{index<3?'Ready':'Pending'}</EuiBadge></div>)}</section>
    <section className="changeOutcomeLedger" data-visual-region="change-outcome-ledger"><EuiTitle size="xs"><h2>Recent outcomes</h2></EuiTitle>{fixture.timeline.slice(0,4).map((item)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><small>{item.status}</small></div>)}</section>
  </div>;
}

export function TaskDispatchConsole({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="taskDispatchConsole" data-visual-region="task-dispatch-console">
    <section className="dispatchPipeline" data-visual-region="dispatch-pipeline"><header><div><EuiBadge color="primary">Dispatch control</EuiBadge><h2>Task execution pipeline</h2></div><strong>18 queued</strong></header>{['Eligible','Queued','Executing','Rehydrating','Completed'].map((stage,index)=><div key={stage}><span>{stage}</span><b>{[32,18,7,4,41][index]}</b><i style={{width:`${[72,48,28,16,88][index]}%`}} /></div>)}</section>
    <aside className="agentCapacityLane" data-visual-region="agent-capacity-lane"><EuiTitle size="xs"><h2>Agent capacity</h2></EuiTitle>{['Fleet East','Fleet West','Cloud workers','Isolated runner'].map((name,index)=><div key={name}><span>{name}</span><EuiProgress value={78-index*13} max={100} size="s" color={index===0?'warning':'primary'} /><small>{4+index} slots</small></div>)}</aside>
    <section className="targetSnapshotInspector" data-visual-region="target-snapshot-inspector"><EuiTitle size="xs"><h2>Target snapshot</h2></EuiTitle><dl><div><dt>Selection</dt><dd>12 visible-page tasks</dd></div><div><dt>Eligible</dt><dd>9</dd></div><div><dt>Requires approval</dt><dd>2</dd></div><div><dt>Revision conflicts</dt><dd>1</dd></div></dl><EuiButtonEmpty>Preview impact</EuiButtonEmpty></section>
    <section className="taskReceiptStream" data-visual-region="task-receipt-stream"><EuiTitle size="xs"><h2>Execution receipts</h2></EuiTitle>{fixture.rows.slice(0,6).map((row,index)=><article key={row.id}><span className={`receiptDot receipt-${index%4}`} /><div><strong>{row.id}</strong><small>request req-{index+100} · actor {row.owner}</small></div><EuiBadge color={index<2?'success':index===2?'warning':'hollow'}>{['completed','completed','executing','queued'][index%4]}</EuiBadge></article>)}</section>
  </div>;
}

export function ResponseActionCommand({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="responseActionCommand" data-visual-region="response-action-command">
    <aside className="actionCatalogRail" data-visual-region="action-catalog-rail"><EuiTitle size="xs"><h2>Response catalog</h2></EuiTitle>{['Isolate host','Disable identity','Block destination','Collect triage'].map((item,index)=><button key={item} type="button" className={index===0?'selected':''}><strong>{item}</strong><small>{index%2?'approval required':'analyst eligible'}</small></button>)}</aside>
    <section className="actionScopeCanvas" data-visual-region="action-scope-canvas"><header><div><EuiBadge color="warning">Impact preview</EuiBadge><h2>Isolate 6 endpoint targets</h2></div><strong>4 eligible</strong></header><div className="targetConstellation">{fixture.rows.slice(0,6).map((row,index)=><span key={row.id} className={index>3?'targetBlocked':''}>{rowText(row,'host',row.id)}<small>{index>3?'Blocked':'Eligible'}</small></span>)}</div><div className="impactSummary"><article><b>4</b><span>eligible</span></article><article><b>1</b><span>approval</span></article><article><b>1</b><span>stale</span></article></div></section>
    <aside className="actionApprovalLane" data-visual-region="action-approval-lane"><EuiTitle size="xs"><h2>Approval chain</h2></EuiTitle><ol><li><b>1</b><span>Capability check</span><EuiBadge color="success">Pass</EuiBadge></li><li><b>2</b><span>Target owner</span><EuiBadge color="warning">Pending</EuiBadge></li><li><b>3</b><span>Execution policy</span><EuiBadge color="hollow">Waiting</EuiBadge></li></ol></aside>
    <section className="actionLifecycleStream" data-visual-region="action-lifecycle-stream"><EuiTitle size="xs"><h2>Action lifecycle</h2></EuiTitle>{['submitted','accepted','queued','executing','rehydrating','completed'].map((status,index)=><div key={status}><span className={index<3?'done':index===3?'active':''} /><strong>{status}</strong><small>{index<3?'Receipt available':index===3?'Agent running':'Not reached'}</small></div>)}</section>
  </div>;
}

export function AssetInventoryWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="assetInventoryWorkspace" data-visual-region="asset-inventory-workspace">
    <aside className="assetFacetRail" data-visual-region="asset-facet-rail"><EuiTitle size="xs"><h2>Inventory facets</h2></EuiTitle>{['Criticality','Owner','Platform','Last seen','Exposure'].map((item,index)=><details key={item} open={index<2}><summary>{item}</summary><label><input type="checkbox" /> High / active</label><label><input type="checkbox" /> Unknown</label></details>)}</aside>
    <section className="assetIdentityGrid" data-visual-region="asset-identity-grid"><header><div><EuiBadge color="primary">Authoritative inventory</EuiBadge><h2>Asset identity board</h2></div><strong>18 visible</strong></header>{fixture.rows.slice(0,8).map((row,index)=><article key={row.id}><div className={`assetGlyph asset-${index%4}`}>{String(row.id).slice(-2)}</div><div><strong>{rowText(row,'canonical_name',row.id)}</strong><small>{rowText(row,'owner',String(row.owner))} · last seen {index+2}m</small></div><div><b>{86-index*5}</b><small>risk</small></div><EuiBadge color={index<2?'danger':index<5?'warning':'success'}>{index<2?'Critical':index<5?'Review':'Healthy'}</EuiBadge></article>)}</section>
    <aside className="assetExposureRail" data-visual-region="asset-exposure-rail"><EuiTitle size="xs"><h2>Exposure context</h2></EuiTitle>{['Critical vulnerabilities','Open alerts','Policy drift','Telemetry gaps'].map((label,index)=><div key={label}><strong>{[12,7,4,2][index]}</strong><span>{label}</span><EuiBadge color={index<2?'danger':'warning'}>{index<2?'Action':'Review'}</EuiBadge></div>)}</aside>
    <section className="assetSourceMatrix" data-visual-region="asset-source-matrix"><EuiTitle size="xs"><h2>Source confidence</h2></EuiTitle>{['Endpoint agent','CMDB','Identity','Cloud inventory'].map((source,index)=><div key={source}><span>{source}</span><EuiProgress value={98-index*6} max={100} size="s" color={index===3?'warning':'primary'} /><small>{98-index*6}%</small></div>)}</section>
  </div>;
}

export function UserIdentityRiskWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="userIdentityRiskWorkspace" data-visual-region="user-identity-risk-workspace">
    <section className="identityDirectory" data-visual-region="identity-directory"><header><div><EuiBadge color="primary">Identity directory</EuiBadge><h2>User access review</h2></div><strong>18 visible</strong></header>{fixture.rows.slice(0,8).map((row,index)=><article key={row.id}><div className="avatarToken">{String(index+1).padStart(2,'0')}</div><div><strong>{rowText(row,'display_name',row.id)}</strong><small>{rowText(row,'group','Security operations')} · MFA {index%3?'enabled':'missing'}</small></div><span>{index+1}h ago</span><EuiBadge color={index===0?'danger':index<3?'warning':'success'}>{index===0?'High risk':index<3?'Review':'Active'}</EuiBadge></article>)}</section>
    <aside className="identityRiskInspector" data-visual-region="identity-risk-inspector"><EuiTitle size="xs"><h2>Account risk</h2></EuiTitle><div className="identityRiskScore"><strong>82</strong><span>High</span></div><ul><li>New impossible travel</li><li>MFA reset 2h ago</li><li>Privileged group membership</li></ul><EuiButtonEmpty>Open access review</EuiButtonEmpty></aside>
    <section className="accessReviewLane" data-visual-region="access-review-lane"><EuiTitle size="xs"><h2>Access review due</h2></EuiTitle>{['Privileged admins','SOC responders','External contractors','Service accounts'].map((group,index)=><div key={group}><strong>{group}</strong><span>{5+index*4} members</span><EuiBadge color={index<2?'warning':'hollow'}>{index<2?'Due soon':'Scheduled'}</EuiBadge></div>)}</section>
  </div>;
}
