import { EuiBadge, EuiButtonEmpty, EuiProgress, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow } from '../../types/prototype';

const value = (row: PrototypeRow, field: string, fallback: string) => String(row[field] ?? fallback);

export function RemediationExecutionWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="remediationExecutionWorkspace" data-visual-region="remediation-execution-workspace">
    <section className="remediationRiskBoard" data-visual-region="remediation-risk-board"><header><div><EuiBadge color="danger">Priority remediation</EuiBadge><h2>Exposure-to-outcome queue</h2></div><strong>{fixture.rows.length} plans</strong></header>{fixture.rows.slice(0,6).map((row,index)=><article key={row.id}><span className="remediationRank">{index+1}</span><div><strong>{value(row,'title',row.id)}</strong><small>{value(row,'target','asset-001')} · {value(row,'owner','Unassigned')}</small></div><div><b>{92-index*7}</b><small>risk</small></div><EuiBadge color={index<2?'danger':index<4?'warning':'hollow'}>{index<2?'Urgent':index<4?'Window':'Planned'}</EuiBadge></article>)}</section>
    <aside className="remediationEligibilityRail" data-visual-region="remediation-eligibility-rail"><EuiTitle size="xs"><h2>Execution eligibility</h2></EuiTitle>{['Target inventory current','Change window available','Approval chain satisfied','Rollback package verified','Validation owner assigned'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index<2?'success':index===2?'warning':'hollow'}>{index<2?'Pass':index===2?'Pending':'Blocked'}</EuiBadge></div>)}</aside>
    <section className="remediationWindowMap" data-visual-region="remediation-window-map"><EuiTitle size="xs"><h2>Windows and dependencies</h2></EuiTitle>{['Identity','Endpoint','Network','Cloud'].map((lane,index)=><div key={lane}><strong>{lane}</strong><span style={{left:`${8+index*7}%`,width:`${22+index*8}%`}}>{index%2?'Change':'Patch'} window</span><small>{index===2?'Collision risk':'Ready'}</small></div>)}</section>
    <section className="remediationOutcomeLedger" data-visual-region="remediation-outcome-ledger"><EuiTitle size="xs"><h2>Outcome verification</h2></EuiTitle>{fixture.timeline.slice(0,5).map((item,index)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><span>{index<2?'Evidence accepted':index===2?'Validation pending':'Not started'}</span></div>)}</section>
  </div>;
}

export function ServiceCatalogRequestWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="serviceCatalogRequestWorkspace" data-visual-region="service-catalog-request-workspace">
    <aside className="catalogCategoryRail" data-visual-region="catalog-category-rail"><EuiTitle size="xs"><h2>Service catalog</h2></EuiTitle>{['Access & identity','Security response','Device services','Cloud services','Data services'].map((item,index)=><button type="button" key={item} className={index===0?'selected':''}><strong>{item}</strong><small>{4+index*3} eligible items</small></button>)}</aside>
    <section className="catalogDiscoveryCanvas" data-visual-region="catalog-discovery-canvas"><header><div><EuiBadge color="primary">Eligible for analyst-01</EuiBadge><h2>Request the right service, not a generic ticket</h2></div><EuiButtonEmpty>Compare items</EuiButtonEmpty></header><div className="catalogCards">{fixture.rows.slice(0,6).map((row,index)=><article key={row.id}><EuiBadge color={index<2?'success':'hollow'}>{index<2?'Recommended':'Available'}</EuiBadge><h3>{value(row,'name',`Catalog item ${index+1}`)}</h3><p>{value(row,'description','Schema-driven request with typed fulfilment and audit receipt.')}</p><footer><span>{1+index%3} approvals</span><span>{2+index}h estimate</span></footer></article>)}</div></section>
    <aside className="requestDraftRail" data-visual-region="request-draft-rail"><EuiTitle size="xs"><h2>Draft request</h2></EuiTitle><dl><div><dt>Requested for</dt><dd>analyst-01</dd></div><div><dt>Service</dt><dd>Identity access</dd></div><div><dt>Schema</dt><dd>catalog-v12</dd></div><div><dt>Approval</dt><dd>Manager + owner</dd></div></dl><EuiProgress value={62} max={100} size="s" /><small>5 of 8 required inputs complete</small></aside>
    <section className="fulfilmentJourney" data-visual-region="fulfilment-journey"><EuiTitle size="xs"><h2>Fulfilment journey</h2></EuiTitle>{['Validate eligibility','Collect typed inputs','Obtain approval','Create fulfilment tasks','Return authoritative receipt'].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span><EuiBadge color={index<2?'success':index===2?'warning':'hollow'}>{index<2?'Ready':index===2?'Review':'Later'}</EuiBadge></div>)}</section>
  </div>;
}

export function CopilotEvidenceWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="copilotEvidenceWorkspace" data-visual-region="copilot-evidence-workspace">
    <section className="copilotConversationCanvas" data-visual-region="copilot-conversation-canvas"><header><div><EuiBadge color="primary">Evidence-grounded session</EuiBadge><h2>Investigate suspicious identity activity</h2></div><span>Context budget 64%</span></header><div className="conversationThread"><article className="analystMessage"><strong>Analyst</strong><p>Explain the failed-login burst and show the strongest evidence.</p></article><article className="assistantMessage"><strong>Copilot</strong><p>The burst begins after a new host trust event. Two sources agree; one identity field is masked by policy.</p><div className="citationRow"><button type="button">[1] Event evt-0012</button><button type="button">[2] Identity audit</button><button type="button">[3] Host relationship</button></div></article></div><footer><textarea aria-label="Copilot prompt" defaultValue="Compare this activity with the previous 24 hours." /><EuiButtonEmpty>Send with evidence</EuiButtonEmpty></footer></section>
    <aside className="copilotEvidenceRail" data-visual-region="copilot-evidence-rail"><EuiTitle size="xs"><h2>Evidence context</h2></EuiTitle>{fixture.rows.slice(0,5).map((row,index)=><article key={row.id}><EuiBadge color={index===2?'warning':'hollow'}>{index===2?'Conflict':'Trusted'}</EuiBadge><strong>{row.id}</strong><small>{value(row,'source','event source')} · {90-index*8}% confidence</small></article>)}</aside>
    <aside className="copilotProposalRail" data-visual-region="copilot-proposal-rail"><EuiTitle size="xs"><h2>Tool proposal</h2></EuiTitle><p>Search correlated identity and endpoint events for the selected scope.</p><dl><div><dt>Capability</dt><dd>events.search</dd></div><div><dt>Scope</dt><dd>identity + endpoint</dd></div><div><dt>Impact</dt><dd>Read only</dd></div><div><dt>Approval</dt><dd>Not required</dd></div></dl><EuiButtonEmpty>Review proposal</EuiButtonEmpty></aside>
  </div>;
}

export function ResponseProjectPortfolio({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="responseProjectPortfolio" data-visual-region="response-project-portfolio">
    <section className="projectOutcomeMap" data-visual-region="project-outcome-map"><header><div><EuiBadge color="primary">Portfolio outcomes</EuiBadge><h2>Response initiatives by measurable risk reduction</h2></div><strong>8 active</strong></header>{fixture.rows.slice(0,5).map((row,index)=><article key={row.id}><div><strong>{value(row,'objective',`Reduce ${['identity','endpoint','network','cloud','data'][index]} risk`)}</strong><small>{value(row,'owner','Program owner')} · sponsor Security</small></div><EuiProgress value={28+index*12} max={100} size="s" /><span>{28+index*12}%</span></article>)}</section>
    <aside className="criticalPathRail" data-visual-region="critical-path-rail"><EuiTitle size="xs"><h2>Critical path</h2></EuiTitle>{['CAB approval','Endpoint rollout','Telemetry validation','Outcome review'].map((item,index)=><div key={item}><b>{index+1}</b><span>{item}</span><EuiBadge color={index===0?'danger':index===1?'warning':'hollow'}>{index===0?'Blocked':index===1?'Active':'Later'}</EuiBadge></div>)}</aside>
    <section className="projectWorkstreamMap" data-visual-region="project-workstream-map"><EuiTitle size="xs"><h2>Workstreams and dependencies</h2></EuiTitle>{['Detection','Remediation','Change','Validation'].map((lane,index)=><div key={lane}><strong>{lane}</strong><span style={{left:`${8+index*4}%`,width:`${32-index*3}%`}}>{index+2} work items</span><small>{index===2?'1 dependency blocked':'On track'}</small></div>)}</section>
    <section className="outcomeEvidenceGate" data-visual-region="outcome-evidence-gate"><EuiTitle size="xs"><h2>Outcome gates</h2></EuiTitle>{['Control deployed','Coverage measured','Residual risk accepted','Evidence retained'].map((gate,index)=><article key={gate}><strong>{gate}</strong><EuiBadge color={index<2?'success':index===2?'warning':'hollow'}>{index<2?'Verified':index===2?'Review':'Pending'}</EuiBadge></article>)}</section>
  </div>;
}

export function RoleCompositionWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="roleCompositionWorkspace" data-visual-region="role-composition-workspace">
    <aside className="rolePortfolioRail" data-visual-region="role-portfolio-rail"><EuiTitle size="xs"><h2>Role portfolio</h2></EuiTitle>{['SOC Analyst','Incident Manager','Change Approver','Detection Engineer','Platform Admin'].map((role,index)=><button type="button" key={role} className={index===0?'selected':''}><strong>{role}</strong><small>{8+index*4} members · rev {3+index}</small></button>)}</aside>
    <section className="entitlementMatrix" data-visual-region="entitlement-matrix"><header><div><EuiBadge color="primary">Effective role composition</EuiBadge><h2>SOC Analyst capabilities by scope</h2></div><strong>14 grants</strong></header><table><thead><tr><th>Capability</th><th>Security</th><th>ITSM</th><th>Runtime</th><th>Export</th></tr></thead><tbody>{['Read','Investigate','Act','Approve','Administer'].map((cap,index)=><tr key={cap}><th>{cap}</th>{[0,1,2,3].map((cell)=><td key={cell}><span className={(index+cell)%3===0?'grant allow':(index+cell)%3===1?'grant conditional':'grant deny'}>{(index+cell)%3===0?'Allow':(index+cell)%3===1?'Conditional':'—'}</span></td>)}</tr>)}</tbody></table></section>
    <aside className="sodConflictRail" data-visual-region="sod-conflict-rail"><EuiTitle size="xs"><h2>SoD conflicts</h2></EuiTitle>{['Rule author + publisher','Requester + approver','Case owner + auditor'].map((item,index)=><div key={item}><strong>{item}</strong><small>{index+1} member{index?'s':''}</small><EuiBadge color={index===0?'danger':'warning'}>Review</EuiBadge></div>)}</aside>
    <section className="roleChangeLedger" data-visual-region="role-change-ledger"><EuiTitle size="xs"><h2>Revision and review ledger</h2></EuiTitle>{fixture.timeline.slice(0,5).map((item)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><span>{item.status}</span></div>)}</section>
  </div>;
}

export function EffectiveAccessExplorer({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="effectiveAccessExplorer" data-visual-region="effective-access-explorer">
    <section className="accessQuestionBuilder" data-visual-region="access-question-builder"><header><div><EuiBadge color="primary">Policy simulation</EuiBadge><h2>Can analyst-01 export restricted events?</h2></div><EuiButtonEmpty>Evaluate</EuiButtonEmpty></header><div className="accessInputs"><label>Subject<input defaultValue="analyst-01" /></label><label>Capability<input defaultValue="events.export" /></label><label>Object<input defaultValue="restricted-event-set" /></label><label>Tenant<input defaultValue="demo" /></label></div></section>
    <aside className="accessDecisionRail" data-visual-region="access-decision-rail"><EuiTitle size="xs"><h2>Decision</h2></EuiTitle><div className="decisionDenied"><strong>DENIED</strong><span>Restricted export capability is not present in current scope.</span></div><dl><div><dt>Decision ID</dt><dd>dec-0042</dd></div><div><dt>Freshness</dt><dd>{fixture.freshness}</dd></div><div><dt>Policy source</dt><dd>tenant-policy-v8</dd></div></dl></aside>
    <section className="policyTraceCanvas" data-visual-region="policy-trace-canvas"><EuiTitle size="xs"><h2>Policy trace</h2></EuiTitle>{['Authenticate subject','Resolve tenant role','Evaluate field classification','Apply export policy','Mask hidden counts'].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span><EuiBadge color={index<3?'success':index===3?'danger':'hollow'}>{index<3?'Pass':index===3?'Deny':'Protected'}</EuiBadge></div>)}</section>
    <section className="grantSourceGraph" data-visual-region="grant-source-graph"><EuiTitle size="xs"><h2>Grant sources</h2></EuiTitle><div className="grantGraph"><span className="principalNode">analyst-01</span><span className="roleNode">SOC Analyst</span><span className="groupNode">Tier 2</span><span className="policyNode">Export policy</span><span className="denyNode">Restricted deny</span></div></section>
  </div>;
}

export function CatalogItemRequestPreview({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="catalogItemRequestPreview" data-visual-region="catalog-item-request-preview">
    <section className="catalogItemIdentity" data-visual-region="catalog-item-identity"><EuiBadge color="success">Available</EuiBadge><h2>Privileged access request</h2><p>Time-bounded access with owner approval, typed justification and automatic expiry.</p><small>Preview generated {fixture.generatedAt}</small><dl><div><dt>Owner</dt><dd>Identity Operations</dd></div><div><dt>SLA</dt><dd>4 business hours</dd></div><div><dt>Audience</dt><dd>SOC analysts</dd></div></dl></section>
    <aside className="eligibilityDecision" data-visual-region="eligibility-decision"><EuiTitle size="xs"><h2>Eligibility</h2></EuiTitle>{['Employee active','MFA enrolled','Training current','No conflicting access'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index<3?'success':'warning'}>{index<3?'Pass':'Review'}</EuiBadge></div>)}</aside>
    <section className="requestSchemaPreview" data-visual-region="request-schema-preview"><EuiTitle size="xs"><h2>Required inputs</h2></EuiTitle>{['Requested role','Business justification','Start and expiry','Target systems','Emergency contact'].map((field,index)=><label key={field}><span>{field}</span><input readOnly value={index===0?'SOC privileged analyst':''} placeholder="Required" /></label>)}</section>
    <section className="fulfilmentFlowMap" data-visual-region="fulfilment-flow-map"><EuiTitle size="xs"><h2>Approval and fulfilment</h2></EuiTitle>{['Submit request','Manager approval','System owner approval','Provision access','Verify and expire'].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span><small>{index<2?'Immediate':index===2?'Within SLA':'Automated'}</small></div>)}</section>
  </div>;
}

export function IdentityGovernanceDetail({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="identityGovernanceDetail" data-visual-region="identity-governance-detail">
    <section className="identityProfileCard" data-visual-region="identity-profile-card"><header><div className="identityAvatar">A1</div><div><EuiBadge color="success">Active</EuiBadge><h2>analyst-01</h2><p>Primary identity from corporate SSO</p></div></header><dl><div><dt>MFA</dt><dd>FIDO2 + TOTP</dd></div><div><dt>Last login</dt><dd>2026-07-17 11:42 UTC</dd></div><div><dt>Risk</dt><dd>Medium</dd></div><div><dt>Owner</dt><dd>Identity Operations</dd></div></dl></section>
    <aside className="identitySourceRail" data-visual-region="identity-source-rail"><EuiTitle size="xs"><h2>Identity sources</h2></EuiTitle>{['Corporate SSO','LDAP directory','SOC local profile','ITSM requester'].map((source,index)=><div key={source}><strong>{source}</strong><small>{index===0?'Authoritative':'Bound'}</small><EuiBadge color={index===0?'success':'hollow'}>{index===0?'Source':'Link'}</EuiBadge></div>)}</aside>
    <section className="effectiveRoleBoard" data-visual-region="effective-role-board"><EuiTitle size="xs"><h2>Effective roles and scopes</h2></EuiTitle>{['SOC Analyst','Case Owner','Event Exporter'].map((role,index)=><article key={role}><strong>{role}</strong><span>{index===0?'security:*':index===1?'assigned cases':'internal data only'}</span><EuiBadge color={index===2?'warning':'primary'}>{index===2?'Conditional':'Active'}</EuiBadge></article>)}</section>
    <section className="sessionSecurityLedger" data-visual-region="session-security-ledger"><EuiTitle size="xs"><h2>Sessions, tokens and changes</h2></EuiTitle>{fixture.timeline.slice(0,5).map((item,index)=><div key={item.time}><time>{item.time}</time><strong>{item.title}</strong><span>{index===0?'Current session':item.status}</span></div>)}</section>
  </div>;
}

export function CopilotEvidenceContextDetail({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="copilotEvidenceContextDetail" data-visual-region="copilot-evidence-context-detail">
    <aside className="evidenceBudgetRail" data-visual-region="evidence-budget-rail"><EuiTitle size="xs"><h2>Context budget</h2></EuiTitle><div className="budgetDial"><strong>64%</strong><span>12,844 tokens</span></div>{['ACL verified','Freshness visible','Conflict retained','Masked fields excluded'].map((item,index)=><div key={item}><span>{item}</span><EuiBadge color={index<3?'success':'warning'}>{index<3?'Pass':'Masked'}</EuiBadge></div>)}</aside>
    <section className="evidenceSelectionCanvas" data-visual-region="evidence-selection-canvas"><header><div><EuiBadge color="primary">Selected evidence</EuiBadge><h2>Context set for identity investigation</h2></div><strong>8 objects</strong></header>{fixture.rows.slice(0,6).map((row,index)=><article key={row.id}><input type="checkbox" defaultChecked={index<4} aria-label={`Select ${row.id}`} /><div><strong>{row.id}</strong><small>{value(row,'source','source')} · {value(row,'status','Ready')}</small></div><span>{86-index*6}% trust</span></article>)}</section>
    <section className="citationRelationshipCanvas" data-visual-region="citation-relationship-canvas"><EuiTitle size="xs"><h2>Citation and conflict map</h2></EuiTitle><div className="citationGraph"><span className="claimNode">Claim</span>{['evt-0012','host-044','identity-a1','audit-77'].map((item,index)=><span key={item} className={`citationNode citation-${index}`}>{item}<small>{index===3?'conflict':'supports'}</small></span>)}</div></section>
    <aside className="contextProvenanceRail" data-visual-region="context-provenance-rail"><EuiTitle size="xs"><h2>Provenance</h2></EuiTitle><dl><div><dt>Scope</dt><dd>Current case + 24h</dd></div><div><dt>Policy</dt><dd>copilot-context-v4</dd></div><div><dt>Revision</dt><dd>12</dd></div><div><dt>Conflicts</dt><dd>1 retained</dd></div></dl></aside>
  </div>;
}

export function MilestonePortfolioRunway({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="milestonePortfolioRunway" data-visual-region="milestone-portfolio-runway">
    <section className="milestoneRunway" data-visual-region="milestone-runway"><header><div><EuiBadge color="primary">Cross-project runway</EuiBadge><h2>Milestones by critical path and evidence gate</h2></div><strong>14 upcoming</strong></header>{['Identity hardening','Endpoint isolation','Network segmentation','Cloud token control'].map((project,index)=><div key={project}><strong>{project}</strong><span className="milestoneBar" style={{left:`${9+index*5}%`,width:`${26+index*7}%`}}>{2+index} milestones</span><small>{index===1?'Blocked dependency':'On track'}</small></div>)}</section>
    <aside className="milestoneRiskRail" data-visual-region="milestone-risk-rail"><EuiTitle size="xs"><h2>Critical path risks</h2></EuiTitle>{['CAB approval delayed','Owner capacity','Evidence incomplete'].map((risk,index)=><article key={risk}><strong>{risk}</strong><small>{index+1} affected milestone{index?'s':''}</small><EuiBadge color={index===0?'danger':'warning'}>Review</EuiBadge></article>)}</aside>
    <section className="milestoneEvidenceMatrix" data-visual-region="milestone-evidence-matrix"><EuiTitle size="xs"><h2>Completion evidence</h2></EuiTitle><table><thead><tr><th>Milestone</th><th>Work state</th><th>Evidence</th><th>Outcome</th></tr></thead><tbody>{fixture.rows.slice(0,5).map((row,index)=><tr key={row.id}><td>{row.id}</td><td>{index<3?'Done':'Active'}</td><td>{index<2?'Verified':index===2?'Partial':'Pending'}</td><td>{index<2?'Accept':'Hold'}</td></tr>)}</tbody></table></section>
    <section className="milestoneDependencyLedger" data-visual-region="milestone-dependency-ledger"><EuiTitle size="xs"><h2>Dependency ledger</h2></EuiTitle>{fixture.relationships.slice(0,5).map((item,index)=><div key={`${item.source}-${item.target}`}><strong>{item.source}</strong><span>{item.relation}</span><strong>{item.target}</strong><EuiBadge color={index===1?'danger':'hollow'}>{index===1?'Blocked':'Clear'}</EuiBadge></div>)}</section>
  </div>;
}
