import { EuiBadge, EuiButtonEmpty, EuiProgress, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow } from '../../types/prototype';

const text = (row: PrototypeRow, field: string, fallback: string) => String(row[field] ?? fallback);

export function RuntimeCapabilityCatalog({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="runtimeCapabilityCatalog" data-visual-region="runtime-capability-catalog">
    <section className="capabilityPortfolio" data-visual-region="capability-portfolio"><header><div><EuiBadge color="primary">Runtime catalog</EuiBadge><h2>Capability portfolio</h2><p>Availability, compatibility and ownership define whether a runtime object can be used.</p></div><strong>12 capabilities</strong></header>{fixture.rows.slice(0,8).map((row,index)=><article key={row.id}><div className={`capabilityIcon capability-${index%4}`}>{['Q','R','A','S'][index%4]}</div><div><strong>{text(row,'name',row.id)}</strong><small>v{3+index}.2 · owner {row.owner}</small></div><div><span>Compatibility</span><EuiProgress value={96-index*5} max={100} size="s" /></div><EuiBadge color={index===2?'warning':'success'}>{index===2?'Degraded':'Available'}</EuiBadge></article>)}</section>
    <aside className="runtimeCompatibilityMap" data-visual-region="runtime-compatibility-map"><EuiTitle size="xs"><h2>Compatibility matrix</h2></EuiTitle><div className="compatibilityMatrix">{Array.from({length:25},(_,index)=><span key={index} className={index%7===0?'incompatible':index%4===0?'conditional':'compatible'}>{index%7===0?'×':index%4===0?'!':'✓'}</span>)}</div><p>Two draft versions require schema migration.</p></aside>
    <section className="runtimeDependencyRail" data-visual-region="runtime-dependency-rail"><EuiTitle size="xs"><h2>Dependency readiness</h2></EuiTitle>{['Search service','Policy engine','Schema registry','Audit store'].map((item,index)=><div key={item}><strong>{item}</strong><span>{index===1?'policy-v8':'ready'}</span><EuiBadge color={index===2?'warning':'success'}>{index===2?'Migration':'Ready'}</EuiBadge></div>)}</section>
    <section className="runtimeOwnershipDirectory" data-visual-region="runtime-ownership-directory"><EuiTitle size="xs"><h2>Ownership</h2></EuiTitle>{['Detection engineering','Platform SRE','Response automation','Data governance'].map((team,index)=><article key={team}><span className="ownerAvatar">{team.slice(0,2)}</span><div><strong>{team}</strong><small>{3+index} capabilities · {index} overdue reviews</small></div></article>)}</section>
  </div>;
}

export function IntegrationTopologyWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="integrationTopologyWorkspace" data-visual-region="integration-topology-workspace">
    <section className="integrationTopologyCanvas" data-visual-region="integration-topology-canvas"><header><div><EuiBadge color="warning">Ingest topology</EuiBadge><h2>Data source connection map</h2></div><strong>1 degraded</strong></header><div className="pipelineTopology"><span className="pipelineCore">Normalize & route</span>{['Endpoint','Identity','Network','Cloud audit','ITSM'].map((name,index)=><span key={name} className={`pipelineNode pipeline-${index}`}>{name}<small>{index===2?'Degraded':'Healthy'}</small></span>)}</div></section>
    <aside className="integrationHealthRail" data-visual-region="integration-health-rail"><EuiTitle size="xs"><h2>Connection health</h2></EuiTitle>{['Endpoint agent','Identity gateway','Edge firewall','Cloud audit'].map((source,index)=><div key={source}><span>{source}</span><b>{index===2?'14m':'<1m'}</b><EuiBadge color={index===2?'danger':'success'}>{index===2?'Lagging':'Streaming'}</EuiBadge></div>)}</aside>
    <section className="ingestPipelineBoard" data-visual-region="ingest-pipeline-board"><EuiTitle size="xs"><h2>Ingest pipeline</h2></EuiTitle>{['Connect','Decode','Normalize','Enrich','Index'].map((stage,index)=><article key={stage}><b>{index+1}</b><div><strong>{stage}</strong><small>{index===2?'Schema warning':'Healthy'}</small></div><EuiProgress value={index===2?72:96-index} max={100} size="s" color={index===2?'warning':'primary'} /></article>)}</section>
    <aside className="integrationRecoveryConsole" data-visual-region="integration-recovery-console"><EuiTitle size="xs"><h2>Recovery console</h2></EuiTitle><dl><div><dt>Failure</dt><dd>Schema field rejected</dd></div><div><dt>Backlog</dt><dd>18,402 events</dd></div><div><dt>Retryable</dt><dd>Yes</dd></div><div><dt>Last good</dt><dd>11:46 UTC</dd></div></dl><EuiButtonEmpty>Run diagnostic</EuiButtonEmpty></aside>
    <section className="schemaConnectionStatus" data-visual-region="schema-connection-status"><EuiTitle size="xs"><h2>Schema status</h2></EuiTitle>{fixture.rows.slice(0,5).map((row,index)=><div key={row.id}><strong>{row.id}</strong><span>schema v{index+3}</span><EuiBadge color={index===2?'warning':'success'}>{index===2?'Drift':'Compatible'}</EuiBadge></div>)}</section>
  </div>;
}

export function KnowledgeIngestionWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="knowledgeIngestionWorkspace" data-visual-region="knowledge-ingestion-workspace">
    <aside className="knowledgeSourceRail" data-visual-region="knowledge-source-rail"><EuiTitle size="xs"><h2>Content sources</h2></EuiTitle>{['Threat reports','Internal runbooks','Vendor advisories','Detection notes'].map((item,index)=><button type="button" key={item} className={index===0?'selected':''}><strong>{item}</strong><small>{12+index*9} documents</small></button>)}</aside>
    <section className="knowledgeIndexingBoard" data-visual-region="knowledge-indexing-board"><header><div><EuiBadge color="primary">Knowledge ingestion</EuiBadge><h2>Indexing operations</h2></div><strong>94% fresh</strong></header>{fixture.rows.slice(0,7).map((row,index)=><article key={row.id}><div className="documentGlyph">DOC</div><div><strong>{text(row,'name',row.id)}</strong><small>{text(row,'owner',String(row.owner))} · classification {index%2?'internal':'confidential'}</small></div><div><EuiProgress value={100-index*7} max={100} size="s" color={index===3?'warning':'primary'} /><small>{index===3?'Stale':'Indexed'}</small></div></article>)}</section>
    <aside className="knowledgeFreshnessInspector" data-visual-region="knowledge-freshness-inspector"><EuiTitle size="xs"><h2>Freshness policy</h2></EuiTitle><div className="freshnessGauge"><strong>94%</strong><span>within policy</span></div><ul><li>2 stale vendor advisories</li><li>1 owner missing</li><li>All confidential sources masked</li></ul></aside>
    <section className="contentClassificationMap" data-visual-region="content-classification-map"><EuiTitle size="xs"><h2>Classification and ownership</h2></EuiTitle>{['Public','Internal','Confidential','Restricted'].map((level,index)=><div key={level}><strong>{level}</strong><span>{18-index*3} sources</span><EuiBadge color={index>1?'warning':'hollow'}>{index>1?'Governed':'Standard'}</EuiBadge></div>)}</section>
  </div>;
}

export function DetectionNotesWorkbench({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="detectionNotesWorkbench" data-visual-region="detection-notes-workbench">
    <aside className="researchNotebookRail" data-visual-region="research-notebook-rail"><EuiTitle size="xs"><h2>Research notebook</h2></EuiTitle>{['Credential access','Cloud persistence','DNS tunneling','Ransomware staging'].map((topic,index)=><button type="button" key={topic} className={index===0?'selected':''}><strong>{topic}</strong><small>rev {8-index} · {index+2} linked rules</small></button>)}</aside>
    <section className="noteEditorCanvas" data-visual-region="note-editor-canvas"><header><div><EuiBadge color="warning">Draft revision</EuiBadge><h2>Credential access research note</h2><p>Author analyst-04 · revision 8 · evidence current</p></div><EuiButtonEmpty>Compare revisions</EuiButtonEmpty></header><article contentEditable suppressContentEditableWarning><h3>Observation</h3><p>Repeated failed logins followed by a privileged session from a newly observed workstation.</p><h3>Detection hypothesis</h3><p>Correlate identity failure bursts, new host trust and privilege changes within a 30-minute window.</p><h3>Evidence</h3><ul><li>Case p04-0007</li><li>Rule p29-0012</li><li>ATT&CK T1110 / T1078</li></ul></article></section>
    <aside className="attackTechniqueRail" data-visual-region="attack-technique-rail"><EuiTitle size="xs"><h2>ATT&CK mapping</h2></EuiTitle>{['T1110 Brute Force','T1078 Valid Accounts','T1098 Account Manipulation'].map((item,index)=><div key={item}><strong>{item}</strong><EuiBadge color={index===0?'danger':'warning'}>{index===0?'Primary':'Related'}</EuiBadge></div>)}</aside>
    <section className="linkedDetectionLedger" data-visual-region="linked-detection-ledger"><EuiTitle size="xs"><h2>Linked rules and evidence</h2></EuiTitle>{fixture.rows.slice(0,5).map((row,index)=><article key={row.id}><strong>{row.id}</strong><span>{index%2?'Evidence':'Detection rule'}</span><small>revision {7-index} · {index+1} citations</small></article>)}</section>
  </div>;
}

export function DetectionRuleStudio({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="detectionRuleStudio" data-visual-region="detection-rule-studio">
    <aside className="rulePortfolioRail" data-visual-region="rule-portfolio-rail"><EuiTitle size="xs"><h2>Rule portfolio</h2></EuiTitle>{fixture.rows.slice(0,6).map((row,index)=><button key={row.id} type="button" className={index===0?'selected':''}><strong>{text(row,'name',row.id)}</strong><small>{index===0?'Draft':'Published'} · rev {11-index}</small></button>)}</aside>
    <section className="ruleQueryAuthoring" data-visual-region="rule-query-authoring"><header><div><EuiBadge color="warning">Draft rule</EuiBadge><h2>Suspicious login sequence</h2></div><span>ES|QL</span></header><pre><code>{`FROM security-events-*\n| WHERE event.category == "authentication"\n| STATS failures = COUNT(*) BY user.name, host.name\n| WHERE failures >= 8`}</code></pre><footer><span>Schema: security.events v4</span><EuiButtonEmpty>Validate query</EuiButtonEmpty></footer></section>
    <aside className="ruleValidationGate" data-visual-region="rule-validation-gate"><EuiTitle size="xs"><h2>Publish gates</h2></EuiTitle>{['Syntax','Field permissions','Dataset coverage','Replay','Approval'].map((gate,index)=><div key={gate}><span>{gate}</span><EuiBadge color={index<3?'success':index===3?'warning':'hollow'}>{index<3?'Pass':index===3?'Running':'Pending'}</EuiBadge></div>)}</aside>
    <section className="ruleReplayBoard" data-visual-region="rule-replay-board"><EuiTitle size="xs"><h2>Exact-event replay</h2></EuiTitle><div className="replayHistogram">{fixture.chart.map((point,index)=><i key={point.label} style={{height:`${point.value}%`}} className={index%4===0?'match':''} />)}</div><table><thead><tr><th>Event</th><th>Match reason</th><th>Result</th></tr></thead><tbody>{fixture.rows.slice(0,4).map((row,index)=><tr key={row.id}><td>{row.id}</td><td>{index%2?'Failure burst':'New host trust'}</td><td>{index%2?'Suppressed':'Matched'}</td></tr>)}</tbody></table></section>
    <section className="ruleOutcomeEstimate" data-visual-region="rule-outcome-estimate"><EuiTitle size="xs"><h2>Estimated outcome</h2></EuiTitle>{['Alerts / day','True positive estimate','Coverage','Review load'].map((label,index)=><article key={label}><strong>{['14','72%','94%','2.1h'][index]}</strong><span>{label}</span></article>)}</section>
  </div>;
}

export function SchemaContractWorkbench({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="schemaContractWorkbench" data-visual-region="schema-contract-workbench">
    <aside className="schemaTreeRail" data-visual-region="schema-tree-rail"><EuiTitle size="xs"><h2>Schema tree</h2></EuiTitle>{['event','host','user','source','network'].map((node,index)=><details key={node} open={index<2}><summary>{node}</summary><span>{node}.id</span><span>{node}.name</span><span>{node}.type</span></details>)}</aside>
    <section className="compatibilityDiffCanvas" data-visual-region="compatibility-diff-canvas"><header><div><EuiBadge color="warning">Revision comparison</EuiBadge><h2>security.events v4 → v5</h2></div><strong>2 breaking</strong></header><div className="schemaDiff"><pre>{`- user.email: keyword\n- event.outcome: optional\n+ user.email: masked_keyword\n+ event.outcome: required`}</pre><pre>{`+ source.confidence: number\n+ ingest.pipeline_id: keyword\n~ host.id: normalized_uuid`}</pre></div><footer><span>Backward compatibility: conditional</span><EuiButtonEmpty>Validate samples</EuiButtonEmpty></footer></section>
    <aside className="consumerImpactRail" data-visual-region="consumer-impact-rail"><EuiTitle size="xs"><h2>Consumer impact</h2></EuiTitle>{['Detection rules','Saved views','Exports','Copilot context'].map((consumer,index)=><div key={consumer}><strong>{consumer}</strong><span>{4+index*3} consumers</span><EuiBadge color={index<2?'danger':'warning'}>{index<2?'Migration':'Review'}</EuiBadge></div>)}</aside>
    <section className="sampleValidationTable" data-visual-region="sample-validation-table"><EuiTitle size="xs"><h2>Sample validation</h2></EuiTitle><table><thead><tr><th>Sample</th><th>v4</th><th>v5</th><th>Issue</th></tr></thead><tbody>{fixture.rows.slice(0,5).map((row,index)=><tr key={row.id}><td>{row.id}</td><td>Valid</td><td>{index<2?'Invalid':'Valid'}</td><td>{index<2?'Missing required field':'—'}</td></tr>)}</tbody></table></section>
    <section className="migrationOrder" data-visual-region="migration-order"><EuiTitle size="xs"><h2>Migration order</h2></EuiTitle>{['Publish shadow schema','Migrate rules','Migrate saved views','Promote v5'].map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span><EuiBadge color={index===0?'success':index===1?'warning':'hollow'}>{index===0?'Ready':index===1?'Next':'Blocked'}</EuiBadge></div>)}</section>
  </div>;
}

export function PlaybookAutomationCanvas({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="playbookAutomationCanvas" data-visual-region="playbook-automation-canvas">
    <aside className="playbookLibraryRail" data-visual-region="playbook-library-rail"><EuiTitle size="xs"><h2>Playbook library</h2></EuiTitle>{['Suspicious login response','Endpoint isolation','Cloud token revoke','Evidence collection'].map((item,index)=><button type="button" key={item} className={index===0?'selected':''}><strong>{item}</strong><small>{index===0?'Draft':'Published'} · {4+index} steps</small></button>)}</aside>
    <section className="automationNodeCanvas" data-visual-region="automation-node-canvas"><header><div><EuiBadge color="warning">Visual draft</EuiBadge><h2>Suspicious login response</h2></div><strong>6 nodes</strong></header><div className="automationGraph"><span className="node trigger">Alert created</span><span className="node search">Search events</span><span className="node decision">Risk ≥ 80?</span><span className="node approval">Analyst approval</span><span className="node action">Disable identity</span><span className="node receipt">Wait for receipt</span></div></section>
    <aside className="automationStepInspector" data-visual-region="automation-step-inspector"><EuiTitle size="xs"><h2>Step inspector</h2></EuiTitle><dl><div><dt>Type</dt><dd>Approval</dd></div><div><dt>Capability</dt><dd>identity.disable</dd></div><div><dt>Timeout</dt><dd>30 minutes</dd></div><div><dt>On timeout</dt><dd>Escalate</dd></div></dl><EuiButtonEmpty>Edit step</EuiButtonEmpty></aside>
    <section className="simulationTrace" data-visual-region="simulation-trace"><EuiTitle size="xs"><h2>Simulation trace</h2></EuiTitle>{fixture.timeline.slice(0,5).map((item,index)=><div key={item.time}><b>{index+1}</b><time>{item.time}</time><span>{item.title}</span><EuiBadge color={index<3?'success':index===3?'warning':'hollow'}>{index<3?'Pass':index===3?'Waiting':'Not run'}</EuiBadge></div>)}</section>
    <section className="automationGovernanceGate" data-visual-region="automation-governance-gate"><EuiTitle size="xs"><h2>Governance</h2></EuiTitle>{['Input schema','Target scope','Approval chain','Receipt mapping','Rollback metadata'].map((gate,index)=><div key={gate}><span>{gate}</span><EuiBadge color={index<3?'success':'warning'}>{index<3?'Ready':'Review'}</EuiBadge></div>)}</section>
  </div>;
}

export function ReportJobCenter({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="reportJobCenter" data-visual-region="report-job-center">
    <aside className="reportCatalogRail" data-visual-region="report-catalog-rail"><EuiTitle size="xs"><h2>Report catalog</h2></EuiTitle>{['SOC weekly outcome','Exposure review','Change risk','Service SLA'].map((item,index)=><button type="button" key={item} className={index===0?'selected':''}><strong>{item}</strong><small>{index%2?'Scheduled':'On demand'}</small></button>)}</aside>
    <section className="exportJobQueue" data-visual-region="export-job-queue"><header><div><EuiBadge color="primary">Background jobs</EuiBadge><h2>Report and export orchestration</h2></div><strong>7 active</strong></header>{fixture.rows.slice(0,7).map((row,index)=><article key={row.id}><div><strong>{text(row,'name',row.id)}</strong><small>{index%2?'Scheduled report':'Ad hoc export'} · confidential</small></div><div><EuiProgress value={index<2?100:78-index*7} max={100} size="s" color={index===3?'warning':'primary'} /><small>{index<2?'Ready':index===3?'Partial':'Queued'}</small></div><EuiBadge color={index<2?'success':index===3?'warning':'hollow'}>{index<2?'Download':index===3?'Review':'Processing'}</EuiBadge></article>)}</section>
    <aside className="deliveryTargetInspector" data-visual-region="delivery-target-inspector"><EuiTitle size="xs"><h2>Delivery & expiry</h2></EuiTitle><dl><div><dt>Target</dt><dd>Secure download</dd></div><div><dt>Classification</dt><dd>Confidential</dd></div><div><dt>Expiry</dt><dd>24 hours</dd></div><div><dt>Redactions</dt><dd>user.email</dd></div></dl><EuiButtonEmpty>View receipt</EuiButtonEmpty></aside>
    <section className="scheduledReportCalendar" data-visual-region="scheduled-report-calendar"><EuiTitle size="xs"><h2>Schedule</h2></EuiTitle>{['Mon','Tue','Wed','Thu','Fri'].map((day,index)=><div key={day}><strong>{day}</strong><span style={{width:`${30+index*11}%`}}>SOC weekly outcome</span></div>)}</section>
  </div>;
}

export function RuntimeObjectGraphWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  return <div className="runtimeObjectGraphWorkspace" data-visual-region="runtime-object-graph-workspace">
    <section className="runtimeObjectGraph" data-visual-region="runtime-object-graph"><header><div><EuiBadge color="primary">Runtime objects</EuiBadge><h2>Object lifecycle and dependencies</h2></div><strong>18 visible</strong></header><div className="objectGraphCanvas"><span className="objectCore">rule-42</span>{['schema-v5','dataset-security','policy-v8','playbook-12','export-view'].map((item,index)=><span key={item} className={`objectNode object-${index}`}>{item}<small>{index===0?'draft':'ready'}</small></span>)}</div></section>
    <aside className="objectLifecycleRail" data-visual-region="object-lifecycle-rail"><EuiTitle size="xs"><h2>Lifecycle</h2></EuiTitle>{['Draft','Validated','Published','Deprecated'].map((state,index)=><div key={state}><b>{index+1}</b><span>{state}</span><EuiBadge color={index===1?'warning':index<1?'success':'hollow'}>{index===1?'Current':index<1?'Done':'Later'}</EuiBadge></div>)}</aside>
    <section className="objectOwnershipInspector" data-visual-region="object-ownership-inspector"><EuiTitle size="xs"><h2>Identity & ownership</h2></EuiTitle><dl><div><dt>Object ID</dt><dd>runtime-rule-42</dd></div><div><dt>Owner</dt><dd>Detection engineering</dd></div><div><dt>Revision</dt><dd>8</dd></div><div><dt>Freshness</dt><dd>{fixture.freshness}</dd></div></dl></section>
    <section className="objectDependencyLedger" data-visual-region="object-dependency-ledger"><EuiTitle size="xs"><h2>Dependency ledger</h2></EuiTitle>{fixture.relationships.slice(0,5).map((rel,index)=><div key={`${rel.source}-${rel.target}`}><strong>{rel.source}</strong><span>{rel.relation}</span><strong>{rel.target}</strong><EuiBadge color={index===0?'warning':'hollow'}>{index===0?'Draft impact':'Ready'}</EuiBadge></div>)}</section>
  </div>;
}
