import { EuiBadge, EuiButtonEmpty, EuiCallOut, EuiFieldText, EuiFormRow, EuiPanel, EuiSpacer, EuiTextArea, EuiTitle } from '@elastic/eui';
import { Link, useLocation } from 'react-router-dom';
import type { TicketBundle } from '../contracts';
import { ticketDetailHref } from '../navigation';

export function TicketDataTab({ bundle, tab }: { bundle: TicketBundle; tab: string }) {
  const location = useLocation();
  const returnTo = `${location.pathname}${location.search}`;
  if (tab === 'Relations') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>Relations</h2></EuiTitle><table><thead><tr><th>Relation</th><th>Target</th><th>Type</th></tr></thead><tbody>{bundle.relations.map((item) => <tr key={item.id}><td>{item.relationType}</td><td><Link to={ticketDetailHref(item.target.id, returnTo, bundle.ticket.key)}>{item.target.title}</Link></td><td>{item.target.kind}</td></tr>)}</tbody></table></EuiPanel>;
  if (tab === 'Approvals') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>Approvals</h2></EuiTitle>{bundle.approvals.length === 0 ? <EuiCallOut title="No approval stages">This ticket type or lifecycle stage has no approval record.</EuiCallOut> : <table><thead><tr><th>Stage</th><th>Approver</th><th>Decision</th><th>Due</th></tr></thead><tbody>{bundle.approvals.map((item) => <tr key={item.id}><td>{item.stage}</td><td>{item.approverId}</td><td><EuiBadge color={item.decision === 'approved' ? 'success' : item.decision === 'rejected' ? 'danger' : 'warning'}>{item.decision}</EuiBadge></td><td>{item.dueAt ?? item.decidedAt ?? '—'}</td></tr>)}</tbody></table>}</EuiPanel>;
  if (tab === 'SLA') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>SLA clocks</h2></EuiTitle>{bundle.slaClocks.map((clock) => <div className="itsmClockRow" key={clock.id}><div><strong>{clock.policyId}</strong><span>{clock.state} · authoritative watermark {clock.authoritativeAt}</span></div><EuiBadge color={clock.state === 'breached' ? 'danger' : clock.state === 'running' ? 'warning' : 'success'}>{clock.remainingSeconds === undefined ? clock.state : `${Math.ceil(clock.remainingSeconds / 60)}m remaining`}</EuiBadge></div>)}<EuiSpacer /><EuiButtonEmpty href="/itsm/sla">Open SLA administration</EuiButtonEmpty></EuiPanel>;
  if (tab === 'Automation') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>Automation context</h2></EuiTitle><EuiCallOut title="Execution boundary">Rules may propose or queue actions. The ticket is not changed until each adapter receipt is rehydrated and audited.</EuiCallOut><EuiSpacer /><EuiButtonEmpty href="/itsm/automation">Open automation administration</EuiButtonEmpty></EuiPanel>;
  if (tab === 'Activity' || tab === 'Audit') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>{tab}</h2></EuiTitle><div className="itsmAuditList">{bundle.auditEvents.map((event) => <article key={event.id}><b>{event.eventType}</b><span>{event.summary}</span><small>{event.createdAt} · {event.actorType}:{event.actorId} · {event.correlationId}</small></article>)}</div></EuiPanel>;
  if (tab === 'RCA' && bundle.ticket.kind === 'problem') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>Root cause analysis</h2></EuiTitle><EuiFormRow label="Root cause"><EuiTextArea value={bundle.ticket.rootCause ?? ''} readOnly rows={5} /></EuiFormRow><EuiFormRow label="Workaround"><EuiTextArea value={bundle.ticket.workaround ?? ''} readOnly rows={5} /></EuiFormRow><EuiCallOut title="Permanent fix linkage">{bundle.ticket.permanentFixChangeId ?? 'No change linked'}</EuiCallOut></EuiPanel>;
  if (['Change plan', 'Implementation', 'Rollback'].includes(tab) && bundle.ticket.kind === 'change') {
    const value = tab === 'Change plan' ? bundle.ticket.validationPlan : tab === 'Implementation' ? bundle.ticket.implementationPlan : bundle.ticket.rollbackPlan;
    return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>{tab}</h2></EuiTitle><EuiTextArea value={value} readOnly rows={8} /><EuiSpacer /><EuiCallOut title="Governed plan">Edits require impact preview, approval/CAB policy evaluation, queued receipt and authoritative refresh.</EuiCallOut></EuiPanel>;
  }
  if (tab === 'Request form' && bundle.ticket.kind === 'request') return <EuiPanel paddingSize="m" hasBorder><EuiTitle size="s"><h2>Schema-driven request form</h2></EuiTitle>{Object.entries(bundle.ticket.dynamicFields).map(([key, value]) => <EuiFormRow key={key} label={key}><EuiFieldText value={String(value)} readOnly /></EuiFormRow>)}</EuiPanel>;
  return <EuiCallOut title={`${tab} is available through its contract`}>This frontend skeleton preserves the tab, loading/error states and API boundary until the corresponding backend endpoint is connected.</EuiCallOut>;
}
