import { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiFormRow, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiSelect, EuiSpacer, EuiStat, EuiTextArea, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';
import { ticketDetailHref, ticketKeyForDetail } from '../../itsm/navigation';

type Tab = 'Catalog' | 'My requests' | 'Fulfilment';
type CatalogItem = { id: string; name: string; category: string; service: string; eligibility: string; approval: string; eta: string; revision: string };
type RequestItem = { id: string; item: string; beneficiary: string; status: string; approval: string; owner: string; sla: string; updated: string };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const catalog: CatalogItem[] = [
  { id:'CAT-001',name:'Privileged access',category:'Access',service:'Identity',eligibility:'Manager + role owner',approval:'2 stages',eta:'4 hours',revision:'r18' },
  { id:'CAT-014',name:'Endpoint software',category:'Device',service:'Endpoint',eligibility:'Managed device',approval:'Auto / exception',eta:'1 business day',revision:'r11' },
  { id:'CAT-023',name:'New data source onboarding',category:'Security',service:'SOC platform',eligibility:'Service owner',approval:'Security review',eta:'3 business days',revision:'r7' },
  { id:'CAT-031',name:'Service account',category:'Identity',service:'Directory',eligibility:'Application owner',approval:'Risk + owner',eta:'2 business days',revision:'r9' },
  { id:'CAT-044',name:'Standard cloud workspace',category:'Cloud',service:'Cloud foundation',eligibility:'Cost centre',approval:'Budget owner',eta:'6 hours',revision:'r5' },
];
const buildRequests = (rows: PrototypeRow[]): RequestItem[] => rows.slice(0, 10).map((row,index)=>({
  id:text(row.request_id,`REQ-${6200+index}`),item:text(row.catalog_item,['Privileged access','Endpoint software','Data source onboarding','Service account'][index%4]),beneficiary:text(row.beneficiary ?? row.requester,`user-${index+1}`),status:text(row.request_status,['Submitted','Approval pending','In fulfilment','Waiting on requester'][index%4]),approval:text(row.approval_state,index%3===0?'Pending':'Approved'),owner:text(row.fulfilment_owner ?? row.owner,['Identity ops','Endpoint team','SOC platform','Directory team'][index%4]),sla:text(row.sla_clocks,index%4===0?'At risk':'Within target'),updated:text(row.updated,`${index+1}h ago`),
}));

export function P15RequestsServiceCatalogWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const location = useLocation();
  const navigate = useNavigate();
  const [tab,setTab]=useState<Tab>('Catalog');
  const [query,setQuery]=useState('');
  const [category,setCategory]=useState('All categories');
  const [selected,setSelected]=useState<CatalogItem>(catalog[0]);
  const [formOpen,setFormOpen]=useState(false);
  const [justification,setJustification]=useState('Business need and requested access scope.');
  const [receipt,setReceipt]=useState<string | undefined>(undefined);
  const requests=useMemo(()=>buildRequests(fixture.rows),[fixture.rows]);
  const visibleCatalog=useMemo(()=>catalog.filter((item)=>(!query.trim()||`${item.name} ${item.category} ${item.service}`.toLowerCase().includes(query.trim().toLowerCase()))&&(category==='All categories'||item.category===category)),[category,query]);
  const openDetail=(id:string)=>navigate(ticketDetailHref(ticketKeyForDetail('request', id), `${location.pathname}${location.search}`, 'Requests & Service Catalog'));
  const submit=()=>{setReceipt(`${selected.name} request submitted to prototype workflow using schema ${selected.revision}. No production request was created.`);setFormOpen(false);setTab('My requests');};
  const tabs:Tab[]=['Catalog','My requests','Fulfilment'];
  return <div className="pageComposition page-p15 differentiatedPage" data-page-specific-composition="P15-catalog-request-fulfilment">
    {receipt&&<><EuiCallOut title="Prototype request receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiPanel paddingSize="m" hasBorder data-visual-region="catalog-tabs-and-scope"><EuiFlexGroup alignItems="center" gutterSize="m"><EuiFlexItem><div className="catalogTabs" role="tablist">{tabs.map((item)=><button type="button" role="tab" aria-selected={tab===item} key={item} onClick={()=>setTab(item)}>{item}</button>)}</div></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color="hollow">Schema-driven forms</EuiBadge></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m" />
    {tab==='Catalog'&&<EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={2}><EuiPanel paddingSize="m" hasBorder data-visual-region="catalog-taxonomy"><EuiTitle size="xs"><h2>Service taxonomy</h2></EuiTitle>{['Access','Device','Security','Identity','Cloud'].map((name,index)=><button type="button" key={name} className={category===name?'selected':''} onClick={()=>setCategory(name)}><strong>{name}</strong><span>{3+index}</span></button>)}</EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="catalog-discovery"><EuiFlexGroup gutterSize="s" alignItems="center"><EuiFlexItem><EuiFieldSearch compressed value={query} onChange={(event:ChangeEvent)=>setQuery(event.target.value)} placeholder="What service or access do you need?" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={category} onChange={(event:ChangeEvent)=>setCategory(event.target.value)} options={['All categories','Access','Device','Security','Identity','Cloud'].map((value)=>({value,text:value}))}/></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m" /><div className="catalogCardGrid">{visibleCatalog.map((item)=><button type="button" key={item.id} className={selected.id===item.id?'selected':''} onClick={()=>setSelected(item)}><EuiBadge color="hollow">{item.category}</EuiBadge><strong>{item.name}</strong><span>{item.service}</span><small>{item.eta} · {item.approval}</small></button>)}</div></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="catalog-item-detail"><EuiTitle size="s"><h2>{selected.name}</h2></EuiTitle><p>{selected.id} · {selected.service}</p><dl><div><dt>Eligibility</dt><dd>{selected.eligibility}</dd></div><div><dt>Approval</dt><dd>{selected.approval}</dd></div><div><dt>Estimated fulfilment</dt><dd>{selected.eta}</dd></div><div><dt>Form revision</dt><dd>{selected.revision}</dd></div></dl><EuiCallOut title="Use a request, not an Incident">This item fulfils a standard service need and follows its own approval/task workflow.</EuiCallOut><EuiSpacer/><EuiButton fill fullWidth onClick={()=>setFormOpen(true)}>Submit request</EuiButton></EuiPanel></EuiFlexItem>
    </EuiFlexGroup>}
    {tab==='My requests'&&<><EuiFlexGroup gutterSize="s" wrap>{[['Open requests',requests.length],['Waiting for approval',requests.filter((item)=>item.approval==='Pending').length],['Fulfilment SLA at risk',requests.filter((item)=>item.sla==='At risk').length]].map(([label,value])=><EuiFlexItem key={String(label)} style={{minWidth:220}}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={String(label)} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup><EuiSpacer size="m"/><EuiPanel paddingSize="m" hasBorder data-visual-region="my-requests-grid"><EuiTitle size="s"><h2>My requests</h2></EuiTitle><table><thead><tr><th>ID/item</th><th>Beneficiary</th><th>Status</th><th>Approval</th><th>Fulfilment owner</th><th>SLA</th><th>Updated</th></tr></thead><tbody>{requests.map((item)=><tr key={item.id}><td><EuiButtonEmpty size="xs" onClick={()=>openDetail(item.id)}>{item.id}</EuiButtonEmpty><small>{item.item}</small></td><td>{item.beneficiary}</td><td>{item.status}</td><td><EuiBadge color={item.approval==='Pending'?'warning':'success'}>{item.approval}</EuiBadge></td><td>{item.owner}</td><td>{item.sla}</td><td>{item.updated}</td></tr>)}</tbody></table></EuiPanel></>}
    {tab==='Fulfilment'&&<EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}><EuiFlexItem grow={6}><EuiPanel paddingSize="m" hasBorder data-visual-region="fulfilment-task-board"><EuiTitle size="s"><h2>Fulfilment tasks</h2></EuiTitle>{requests.slice(0,7).map((item,index)=><article key={item.id}><div><strong>{item.id} · {item.item}</strong><small>{item.beneficiary} · {item.owner}</small></div><span>{['Validate eligibility','Collect approval','Provision service','Verify outcome'][index%4]}</span><EuiBadge color={index<2?'warning':'hollow'}>{item.sla}</EuiBadge><EuiButtonEmpty size="xs" onClick={()=>setReceipt(`Task update for ${item.id} queued in prototype mode.`)}>Update task</EuiButtonEmpty></article>)}</EuiPanel></EuiFlexItem><EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="fulfilment-demand"><EuiTitle size="xs"><h2>Request demand by service</h2></EuiTitle>{['Identity','Endpoint','SOC platform','Cloud'].map((name,index)=><div key={name}><span>{name}</span><strong>{12-index*2}</strong><small>{index%2?'stable':'rising'}</small></div>)}<table><caption>Exact demand values</caption><tbody>{['Identity','Endpoint','SOC platform','Cloud'].map((name,index)=><tr key={name}><td>{name}</td><td>{12-index*2}</td></tr>)}</tbody></table></EuiPanel></EuiFlexItem></EuiFlexGroup>}
    {formOpen&&<EuiModal onClose={()=>setFormOpen(false)} aria-labelledby="p15-form-title"><EuiModalHeader><EuiModalHeaderTitle id="p15-form-title">{selected.name} request</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title={`Form schema ${selected.revision}`}>Eligibility, required fields and approval are bound to this catalog-item revision.</EuiCallOut><EuiSpacer/><EuiFormRow label="Beneficiary"><EuiFieldSearch value="analyst-01" readOnly /></EuiFormRow><EuiFormRow label="Business justification"><EuiTextArea value={justification} onChange={(event:ChangeEvent)=>setJustification(event.target.value)} /></EuiFormRow><EuiFormRow label="Requested duration"><EuiSelect options={[{value:'8h',text:'8 hours'},{value:'7d',text:'7 days'},{value:'30d',text:'30 days'}]} /></EuiFormRow></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={()=>setFormOpen(false)}>Save draft</EuiButtonEmpty><EuiButton fill onClick={submit}>Submit prototype request</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}
