import { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiFieldSearch, EuiFlexGroup, EuiFlexItem,
  EuiFlyout, EuiFlyoutBody, EuiFlyoutFooter, EuiFlyoutHeader, EuiModal, EuiModalBody,
  EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiProgress, EuiSelect,
  EuiSpacer, EuiStat, EuiTitle,
} from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';
import { ticketDetailHref, ticketKeyForDetail } from '../../itsm/navigation';

type Change = { id:string; summary:string; service:string; risk:string; state:string; window:string; owner:string; approvals:string; collision:string; rollback:string; validation:string };
type ChangeEvent = { target: { value: string } };
type View = 'Calendar' | 'Queue' | 'CAB';
const text=(value:PrototypeValue|undefined,fallback:string)=>value===undefined?fallback:String(value);
const buildChanges=(rows:PrototypeRow[]):Change[]=>rows.slice(0,12).map((row,index)=>({
  id:text(row.change_id,`CHG-${8200+index}`),summary:text(row.summary??row.title,['Identity provider rollout','Endpoint policy deployment','Database failover rehearsal','Network segmentation change'][index%4]),
  service:text(row.service_ci,['Identity','Endpoint','Customer API','Network'][index%4]),risk:text(row.risk,index<2?'High':index<6?'Medium':'Low'),
  state:text(row.change_state,['Assessment','CAB pending','Scheduled','Implementing','Validation'][index%5]),window:text(row.change_window,`Jul ${21+(index%5)} · ${String(20+index%4).padStart(2,'0')}:00`),
  owner:text(row.owner,'Change management'),approvals:text(row.approval_state,index%4===0?'Missing security approval':'Ready'),collision:text(row.collision,index%5===0?'Incident overlap':index%5===1?'Shared CI conflict':'None'),
  rollback:text(row.rollback_readiness,index%3===0?'Incomplete':'Ready'),validation:text(row.validation_state,index%4===3?'Running':'Not started'),
}));

export function P18ChangeManagementWorkspace({fixture}:{fixture:PrototypePageFixture}){
  const location=useLocation();
  const navigate=useNavigate();
  const[view,setView]=useState<View>('Calendar');
  const[query,setQuery]=useState('');
  const[risk,setRisk]=useState('All risk');
  const[selectedId,setSelectedId]=useState<string|undefined>(undefined);
  const[detailOpen,setDetailOpen]=useState(false);
  const[decisionOpen,setDecisionOpen]=useState(false);
  const[receipt,setReceipt]=useState<string|undefined>(undefined);
  const changes=useMemo(()=>buildChanges(fixture.rows),[fixture.rows]);
  const visible=useMemo(()=>changes.filter((item)=>(!query.trim()||`${item.id} ${item.summary} ${item.service} ${item.owner}`.toLowerCase().includes(query.trim().toLowerCase()))&&(risk==='All risk'||item.risk===risk)),[changes,query,risk]);
  const selected=visible.find((item)=>item.id===selectedId)??visible[0]??changes[0];
  if(!selected)return null;
  const openDetail=(id:string)=>navigate(ticketDetailHref(ticketKeyForDetail('change', id), `${location.pathname}${location.search}`, 'Change Management'));
  const queue=(label:string)=>setReceipt(`${label} queued for ${selected.id}. Approval, implementation and completion remain separate authoritative states.`);
  const metrics={conflicts:changes.filter((item)=>item.collision!=='None').length,missing:changes.filter((item)=>/missing/i.test(item.approvals)).length,rollback:changes.filter((item)=>item.rollback!=='Ready').length,implementing:changes.filter((item)=>item.state==='Implementing').length};
  return <div className="pageComposition page-p18 differentiatedPage" data-page-specific-composition="P18-change-calendar-cab-governance">
    <EuiPanel paddingSize="m" hasBorder data-visual-region="change-scope-tabs"><EuiFlexGroup alignItems="center" gutterSize="m"><EuiFlexItem><div className="changeTabs" role="tablist">{(['Calendar','Queue','CAB'] as View[]).map((item)=><button type="button" role="tab" aria-selected={view===item} key={item} onClick={()=>setView(item)}>{item}</button>)}</div></EuiFlexItem><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event:ChangeEvent)=>setQuery(event.target.value)} placeholder="Change, service, CI, owner or implementation window"/></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={risk} onChange={(event:ChangeEvent)=>setRisk(event.target.value)} options={['All risk','High','Medium','Low'].map((value)=>({value,text:value}))}/></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={()=>setReceipt('Create Change wizard opened in prototype mode; no production Change was created.')}>Create change</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m"/>{receipt&&<><EuiCallOut title="Prototype Change receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m"/></>}
    <EuiFlexGroup gutterSize="s" wrap>{[['Window conflicts',metrics.conflicts],['Missing approvals',metrics.missing],['Rollback gaps',metrics.rollback],['Implementing now',metrics.implementing]].map(([label,value])=><EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s"/></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
    <EuiSpacer size="m"/>
    {view==='Calendar'&&<EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}><EuiFlexItem grow={7}><EuiPanel paddingSize="m" hasBorder data-visual-region="change-calendar"><EuiTitle size="s"><h2>Implementation calendar</h2></EuiTitle><div className="changeCalendarHeader"><span>Service</span>{['Mon 21','Tue 22','Wed 23','Thu 24','Fri 25'].map((day)=><b key={day}>{day}</b>)}</div>{['Identity','Endpoint','Customer API','Network'].map((serviceName,laneIndex)=><div className="changeCalendarLane" key={serviceName}><strong>{serviceName}</strong>{visible.filter((item)=>item.service===serviceName).slice(0,3).map((item,index)=><button type="button" key={item.id} className={item.collision!=='None'?'collision':''} style={{gridColumn:`${2+((laneIndex+index)%5)}`}} onClick={()=>setSelectedId(item.id)}>{item.id}<small>{item.risk} · {item.state}</small></button>)}</div>)}</EuiPanel></EuiFlexItem><EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="calendar-conflict-inspector"><EuiTitle size="xs"><h2>Conflict inspector</h2></EuiTitle>{visible.filter((item)=>item.collision!=='None').slice(0,5).map((item)=><button key={item.id} type="button" onClick={()=>setSelectedId(item.id)}><strong>{item.id}</strong><span>{item.collision}</span><EuiBadge color="danger">Review</EuiBadge></button>)}</EuiPanel></EuiFlexItem></EuiFlexGroup>}
    {view==='Queue'&&<EuiPanel paddingSize="m" hasBorder data-visual-region="change-queue"><table><thead><tr><th>Change</th><th>Service</th><th>Risk</th><th>State</th><th>Window</th><th>Approval</th><th>Collision</th></tr></thead><tbody>{visible.map((item)=><tr key={item.id}><td><EuiButtonEmpty size="xs" onClick={()=>openDetail(item.id)}>{item.id}</EuiButtonEmpty><small>{item.summary}</small></td><td>{item.service}</td><td><EuiBadge color={item.risk==='High'?'danger':item.risk==='Medium'?'warning':'success'}>{item.risk}</EuiBadge></td><td>{item.state}</td><td>{item.window}</td><td>{item.approvals}</td><td>{item.collision}</td></tr>)}</tbody></table></EuiPanel>}
    {view==='CAB'&&<EuiFlexGroup gutterSize="m" responsive={false}><EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="cab-decision-queue"><EuiTitle size="s"><h2>CAB decision queue</h2></EuiTitle>{visible.filter((item)=>item.state==='CAB pending'||item.risk==='High').map((item)=><button type="button" key={item.id} onClick={()=>setSelectedId(item.id)}><div><strong>{item.id}</strong><span>{item.summary}</span><small>{item.service} · {item.window}</small></div><EuiBadge color={item.approvals.startsWith('Missing')?'danger':'warning'}>{item.approvals}</EuiBadge></button>)}</EuiPanel></EuiFlexItem><EuiFlexItem grow={6}><EuiPanel paddingSize="m" hasBorder data-visual-region="cab-impact-review"><EuiTitle size="s"><h2>{selected.id} impact review</h2></EuiTitle><div className="changeImpactGraph"><span className="impactCore">{selected.service}</span>{['Primary CI','Dependent service','Incident overlap','Monitoring'].map((label,index)=><span key={label} className={`node node-${index}`}>{label}<small>{index===2?selected.collision:index===3?selected.validation:'Affected'}</small></span>)}</div><EuiSpacer/><EuiTitle size="xs"><h3>Execution readiness</h3></EuiTitle>{[['Approvals',selected.approvals],['Rollback',selected.rollback],['Validation',selected.validation],['Owner',selected.owner]].map(([label,value],index)=><div key={label}><strong>{label}</strong><span>{value}</span><EuiProgress value={index===0&&selected.approvals.startsWith('Missing')?35:index===1&&selected.rollback!=='Ready'?45:85} max={100} size="s" color={index<2?'warning':'primary'}/></div>)}<EuiSpacer/><EuiFlexGroup gutterSize="s"><EuiFlexItem grow={false}><EuiButton fill onClick={()=>setDecisionOpen(true)}>Review CAB decision</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty onClick={()=>setDetailOpen(true)}>Plan preview</EuiButtonEmpty><EuiButtonEmpty onClick={()=>openDetail(selected.id)}>Open shared detail</EuiButtonEmpty></EuiFlexItem></EuiFlexGroup></EuiPanel></EuiFlexItem></EuiFlexGroup>}
    {detailOpen&&<EuiFlyout onClose={()=>setDetailOpen(false)} ownFocus size="m" aria-labelledby="p18-detail-title"><EuiFlyoutHeader><EuiTitle><h2 id="p18-detail-title">Change plan and rollback</h2></EuiTitle></EuiFlyoutHeader><EuiFlyoutBody><EuiCallOut title="Approval is not execution">Approved, scheduled, implementing, validating and completed remain distinct states.</EuiCallOut><EuiSpacer/>{['Pre-check','Implementation step 1','Implementation step 2','Validation','Rollback trigger'].map((step,index)=><div key={step}><b>{index+1}</b><strong>{step}</strong><span>{index<2?'Ready':'Pending'}</span></div>)}</EuiFlyoutBody><EuiFlyoutFooter><EuiButton onClick={()=>setDetailOpen(false)}>Close</EuiButton></EuiFlyoutFooter></EuiFlyout>}
    {decisionOpen&&<EuiModal onClose={()=>setDecisionOpen(false)} aria-labelledby="p18-decision-title"><EuiModalHeader><EuiModalHeaderTitle id="p18-decision-title">CAB impact confirmation</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="Prototype governed decision" color="warning">The demo records a decision receipt only. It does not approve or execute the production Change.</EuiCallOut><ul><li>Risk: {selected.risk}</li><li>Collision: {selected.collision}</li><li>Rollback: {selected.rollback}</li><li>Validation: {selected.validation}</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={()=>setDecisionOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={()=>{queue('CAB approval decision');setDecisionOpen(false);}}>Queue decision</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}
