import { useMemo, useState } from 'react';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiProgress, EuiSelect, EuiSpacer, EuiStat, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';

type Agent = { key: string; id: string; name: string; site: string; health: string; readiness: string; version: string; approved: string; capabilities: string[]; running: number; capacity: number; heartbeat: string; policy: string; drift: string };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const number = (value: PrototypeValue | undefined, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const buildAgents = (rows: PrototypeRow[]): Agent[] => rows.slice(0, 14).map((row, index) => ({
  key: `${row.id}:${index}`,
  id: text(row.agent_id, `agt-${String(index + 1).padStart(3, '0')}`), name: text(row.agent_name, `SOC agent ${index + 1}`), site: text(row.site, ['Taipei','Singapore','Frankfurt','Cloud pool'][index % 4]),
  health: text(row.health, index % 6 === 0 ? 'Offline' : index % 5 === 0 ? 'Degraded' : 'Online'), readiness: text(row.readiness, index % 4 === 0 ? 'Drain required' : 'Ready'), version: text(row.version, `3.${8 - (index % 3)}.${index % 5}`), approved: '3.8.x',
  capabilities: ['collect.telemetry', index % 2 ? 'execute.response' : 'query.events', index % 3 ? 'upload.artifact' : 'run.script'], running: number(row.running_tasks, index % 5), capacity: number(row.capacity, 4 + (index % 4)), heartbeat: text(row.heartbeat_age, `${1 + index}m`), policy: text(row.policy_revision, `fleet-policy@r${12 - index % 3}`), drift: index % 5 === 0 ? 'Version drift' : index % 7 === 0 ? 'Policy drift' : 'Aligned',
}));

export function P24AgentFleetWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const [query, setQuery] = useState(''); const [site, setSite] = useState('All sites'); const [health, setHealth] = useState('All health'); const [selectedKey, setSelectedKey] = useState<string | undefined>(undefined); const [rolloutOpen, setRolloutOpen] = useState(false); const [receipt, setReceipt] = useState<string | undefined>(undefined);
  const agents = useMemo(() => buildAgents(fixture.rows), [fixture.rows]);
  const visible = useMemo(() => agents.filter((item) => (!query.trim() || `${item.id} ${item.name} ${item.site} ${item.version} ${item.capabilities.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())) && (site === 'All sites' || item.site === site) && (health === 'All health' || item.health === health)), [agents, health, query, site]);
  const selected = visible.find((item) => item.key === selectedKey) ?? visible[0] ?? agents[0]; if (!selected) return null;
  const metrics = { ready: agents.filter((item) => item.health === 'Online' && item.readiness === 'Ready').length, unavailable: agents.filter((item) => item.health !== 'Online').length, capacity: agents.filter((item) => item.running >= item.capacity).length, drift: agents.filter((item) => item.drift !== 'Aligned').length, failed: 7 };
  const action = (label: string) => setReceipt(`${label} queued for ${selected.id}; fleet state remains unchanged until the agent registry rehydrates the authoritative result.`);
  return <div className="pageComposition page-p24 differentiatedPage" data-page-specific-composition="P24-agent-fleet-readiness-rollout">
    <EuiPanel paddingSize="m" hasBorder data-visual-region="fleet-scope-bar"><EuiFlexGroup gutterSize="s" alignItems="center" wrap><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event: ChangeEvent) => setQuery(event.target.value)} placeholder="Agent, site, capability, version or policy" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={site} onChange={(event: ChangeEvent) => setSite(event.target.value)} options={['All sites','Taipei','Singapore','Frankfurt','Cloud pool'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={health} onChange={(event: ChangeEvent) => setHealth(event.target.value)} options={['All health','Online','Degraded','Offline'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={() => setReceipt('Register agent wizard opened in prototype mode; no registry record was created.')}>Register agent</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m" />{receipt && <><EuiCallOut title="Prototype fleet receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiFlexGroup gutterSize="s" wrap data-visual-region="fleet-kpi-summary">{[['Online and ready', metrics.ready],['Degraded/offline', metrics.unavailable],['At capacity', metrics.capacity],['Policy/version drift', metrics.drift],['Failed tasks 24h', metrics.failed]].map(([label, value]) => <EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
    <EuiSpacer size="m" /><EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={6}><EuiPanel paddingSize="m" hasBorder data-visual-region="fleet-agent-grid"><EuiTitle size="s"><h2>Agent readiness grid</h2></EuiTitle><table><thead><tr><th>Agent</th><th>Site</th><th>Health</th><th>Readiness</th><th>Version</th><th>Capacity</th><th>Drift</th></tr></thead><tbody>{visible.map((item) => <tr key={item.key}><td><EuiButtonEmpty size="xs" onClick={() => setSelectedKey(item.key)}>{item.id}</EuiButtonEmpty><small>{item.name}</small></td><td>{item.site}</td><td><EuiBadge color={item.health === 'Online' ? 'success' : item.health === 'Degraded' ? 'warning' : 'danger'}>{item.health}</EuiBadge></td><td>{item.readiness}</td><td>{item.version}</td><td><EuiProgress value={item.running} max={item.capacity} size="s" color={item.running >= item.capacity ? 'warning' : 'primary'} />{item.running}/{item.capacity}</td><td>{item.drift}</td></tr>)}</tbody></table></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="fleet-agent-detail"><EuiFlexGroup alignItems="center"><EuiFlexItem><EuiTitle size="s"><h2>{selected.name}</h2></EuiTitle><p>{selected.id} · {selected.site} · heartbeat {selected.heartbeat}</p></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color={selected.drift === 'Aligned' ? 'success' : 'warning'}>{selected.drift}</EuiBadge></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m" /><dl><div><dt>Version</dt><dd>{selected.version} / approved {selected.approved}</dd></div><div><dt>Policy</dt><dd>{selected.policy}</dd></div><div><dt>Effective capacity</dt><dd>{selected.capacity}</dd></div><div><dt>Running tasks</dt><dd>{selected.running}</dd></div></dl><EuiTitle size="xs"><h3>Capabilities</h3></EuiTitle>{selected.capabilities.map((item) => <EuiBadge key={item} color={item.includes('response') ? 'warning' : 'hollow'}>{item}</EuiBadge>)}<EuiSpacer size="m" /><EuiFlexGroup gutterSize="s" wrap><EuiFlexItem grow={false}><EuiButton onClick={() => action('Drain agent')}>Drain</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButton color="danger" onClick={() => action('Disable agent')}>Disable</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty onClick={() => setRolloutOpen(true)}>Review rollout</EuiButtonEmpty></EuiFlexItem></EuiFlexGroup></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="fleet-pool-capacity"><EuiTitle size="xs"><h2>Pool capacity</h2></EuiTitle>{['Taipei','Singapore','Frankfurt','Cloud pool'].map((name, index) => <div key={name}><strong>{name}</strong><EuiProgress value={78 - index * 13} max={100} size="s" color={index === 0 ? 'warning' : 'primary'} /><span>{6 + index} slots</span></div>)}<EuiSpacer /><EuiCallOut title="Rollout constraint" size="s">Keep at least two ready agents per critical site and preserve a rollback version.</EuiCallOut></EuiPanel></EuiFlexItem>
    </EuiFlexGroup>
    {rolloutOpen && <EuiModal onClose={() => setRolloutOpen(false)} aria-labelledby="p24-rollout-title"><EuiModalHeader><EuiModalHeaderTitle id="p24-rollout-title">Version and policy rollout</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="Capacity and rollback gate" color="warning">Rollout is queued only if site capacity, task drain and rollback conditions remain valid.</EuiCallOut><ul><li>Target: {selected.id}</li><li>Current: {selected.version}</li><li>Approved: {selected.approved}</li><li>Running tasks: {selected.running}</li><li>Rollback package: available</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={() => setRolloutOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={() => { action('Controlled rollout'); setRolloutOpen(false); }}>Queue rollout</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}