import { useMemo, useState } from 'react';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiCodeBlock, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiSelect, EuiSpacer, EuiStat, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';

type Task = { id: string; type: string; source: string; target: string; pool: string; state: string; approval: string; attempt: number; queue: string; execution: string; idempotency: string; sideEffects: string; retryable: boolean };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const number = (value: PrototypeValue | undefined, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const buildTasks = (rows: PrototypeRow[]): Task[] => rows.slice(0, 15).map((row, index) => ({ id: text(row.task_id, `TASK-${9200 + index}`), type: text(row.task_type, ['Collect triage','Isolate host','Run script','Query telemetry'][index % 4]), source: text(row.source_ref, [`CASE-${810 + index}`,`CHG-${820 + index}`,`ACT-${260 + index}`,`INC-${7000 + index}`][index % 4]), target: text(row.target_ref, `asset-${30 + index}`), pool: text(row.agent_pool, ['Taipei','Cloud pool','Endpoint fleet','Restricted runner'][index % 4]), state: text(row.state, ['Pending approval','Queued','Running','Failed','Partial','Completed'][index % 6]), approval: text(row.approval_state, index % 4 === 0 ? 'Pending' : 'Approved'), attempt: number(row.attempt, 1 + (index % 3)), queue: text(row.queue_time, `${2 + index}m`), execution: text(row.execution_time, `${8 + index * 2}m`), idempotency: text(row.idempotency_key, `idem-${9200 + index}-r1`), sideEffects: text(row.side_effects, index % 5 === 4 ? 'Partial host isolation' : 'None observed'), retryable: index % 5 !== 4 }));

export function P25TaskDispatchWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const [query, setQuery] = useState(''); const [state, setState] = useState('Active and failed'); const [pool, setPool] = useState('All pools'); const [selectedId, setSelectedId] = useState<string | undefined>(undefined); const [dispatchOpen, setDispatchOpen] = useState(false); const [receipt, setReceipt] = useState<string | undefined>(undefined);
  const tasks = useMemo(() => buildTasks(fixture.rows), [fixture.rows]);
  const visible = useMemo(() => tasks.filter((item) => (!query.trim() || `${item.id} ${item.type} ${item.source} ${item.target} ${item.pool}`.toLowerCase().includes(query.trim().toLowerCase())) && (state === 'All states' || (state === 'Active and failed' ? ['Pending approval','Queued','Running','Failed','Partial'].includes(item.state) : item.state === state)) && (pool === 'All pools' || item.pool === pool)), [pool, query, state, tasks]);
  const selected = visible.find((item) => item.id === selectedId) ?? visible[0] ?? tasks[0]; if (!selected) return null;
  const counts = { pending: tasks.filter((item) => item.state === 'Pending approval').length, queued: tasks.filter((item) => item.state === 'Queued').length, running: tasks.filter((item) => item.state === 'Running').length, failed: tasks.filter((item) => ['Failed','Partial'].includes(item.state)).length, median: '8m' };
  const action = (label: string) => setReceipt(`${label} queued for ${selected.id}. Scheduler, agent execution and authoritative result remain separate states.`);
  return <div className="pageComposition page-p25 differentiatedPage" data-page-specific-composition="P25-task-scheduler-attempt-receipt">
    <EuiPanel paddingSize="m" hasBorder data-visual-region="task-scope-bar"><EuiFlexGroup gutterSize="s" alignItems="center" wrap><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event: ChangeEvent) => setQuery(event.target.value)} placeholder="Task, source Case/Change, target, pool or idempotency key" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={state} onChange={(event: ChangeEvent) => setState(event.target.value)} options={['Active and failed','All states','Pending approval','Queued','Running','Failed','Partial','Completed'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={pool} onChange={(event: ChangeEvent) => setPool(event.target.value)} options={['All pools','Taipei','Cloud pool','Endpoint fleet','Restricted runner'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={() => setDispatchOpen(true)}>Dispatch task</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m" />{receipt && <><EuiCallOut title="Prototype task receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiFlexGroup gutterSize="s" wrap>{[['Pending approval', counts.pending],['Queued', counts.queued],['Running', counts.running],['Failed/partial 24h', counts.failed],['Median queue time', counts.median]].map(([label, value]) => <EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
    <EuiSpacer size="m" /><EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="task-dispatch-grid"><EuiTitle size="s"><h2>Scheduler queue and attempts</h2></EuiTitle><table><thead><tr><th>Task</th><th>Type/source</th><th>Target</th><th>Pool</th><th>State</th><th>Attempt</th><th>Queue/execution</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><EuiButtonEmpty size="xs" onClick={() => setSelectedId(item.id)}>{item.id}</EuiButtonEmpty></td><td>{item.type}<small>{item.source}</small></td><td>{item.target}</td><td>{item.pool}</td><td><EuiBadge color={item.state === 'Completed' ? 'success' : ['Failed','Partial'].includes(item.state) ? 'danger' : 'warning'}>{item.state}</EuiBadge></td><td>{item.attempt}</td><td>{item.queue} / {item.execution}</td></tr>)}</tbody></table></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="task-target-attempt-detail"><EuiFlexGroup alignItems="center"><EuiFlexItem><EuiTitle size="s"><h2>{selected.type}</h2></EuiTitle><p>{selected.id} · {selected.source}</p></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color={selected.retryable ? 'success' : 'danger'}>{selected.retryable ? 'Retryable' : 'Manual recovery'}</EuiBadge></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m" /><div className="taskStatePipeline">{['Requested','Approved','Queued','Running','Rehydrating','Completed'].map((stage, index) => <div key={stage}><b>{index + 1}</b><span>{stage}</span><small>{index < selected.attempt + 2 ? 'Reached' : 'Pending'}</small></div>)}</div><EuiSpacer size="m" /><dl><div><dt>Target snapshot</dt><dd>{selected.target} · revision r18</dd></div><div><dt>Agent pool</dt><dd>{selected.pool}</dd></div><div><dt>Idempotency</dt><dd>{selected.idempotency}</dd></div><div><dt>Partial side effects</dt><dd>{selected.sideEffects}</dd></div></dl><EuiCodeBlock language="text" paddingSize="s">attempt {selected.attempt}: scheduler accepted → agent claimed → execution heartbeat → {selected.state}</EuiCodeBlock><EuiSpacer size="m" /><EuiFlexGroup gutterSize="s" wrap><EuiFlexItem grow={false}><EuiButton onClick={() => action('Cancel task')} isDisabled={selected.state === 'Completed'}>Cancel</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={() => action('Retry task')} isDisabled={!selected.retryable}>Retry</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty onClick={() => action('Reassign task')}>Reassign</EuiButtonEmpty></EuiFlexItem></EuiFlexGroup></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={2}><EuiPanel paddingSize="m" hasBorder data-visual-region="task-receipt-ledger"><EuiTitle size="xs"><h2>Attempt receipts</h2></EuiTitle>{tasks.slice(0, 6).map((item) => <div key={item.id}><strong>{item.id}</strong><span>attempt {item.attempt}</span><EuiBadge color={item.state === 'Completed' ? 'success' : 'hollow'}>{item.state}</EuiBadge></div>)}</EuiPanel></EuiFlexItem>
    </EuiFlexGroup>
    {dispatchOpen && <EuiModal onClose={() => setDispatchOpen(false)} aria-labelledby="p25-dispatch-title"><EuiModalHeader><EuiModalHeaderTitle id="p25-dispatch-title">Dispatch target and impact</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="Governed dispatch" color="warning">The prototype freezes target revision, inputs and idempotency, then queues a task. It does not execute production automation.</EuiCallOut><ul><li>Target snapshot: asset-031@r18</li><li>Pool: Endpoint fleet</li><li>Approval: required</li><li>Idempotency: generated before queue</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={() => setDispatchOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={() => { action('Dispatch task'); setDispatchOpen(false); }}>Queue dispatch</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}
