import { useMemo, useState } from 'react';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiCodeBlock, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiFormRow, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiSelect, EuiSpacer, EuiStat, EuiSwitch, EuiTextArea, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';

type Policy = { id: string; subject: string; capability: string; resource: string; effect: string; conditions: string; risk: string; state: string; hits: number; expiry: string; revision: string; conflict: string };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const number = (value: PrototypeValue | undefined, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const buildPolicies = (rows: PrototypeRow[]): Policy[] => rows.slice(0, 12).map((row, index) => ({ id: text(row.policy_id, `POL-${5100 + index}`), subject: text(row.agent_scope, `fleet:${['endpoint','cloud','restricted','taipei'][index % 4]}`), capability: text(row.capability, ['execute.response','query.events','run.script','read.artifact'][index % 4]), resource: text(row.resource_scope, [`site:${['prod','corp','cloud','isolated'][index % 4]}`,`dataset:security-${index % 3}`][index % 2]), effect: text(row.effect, index % 6 === 0 ? 'Deny' : 'Allow'), conditions: text(row.conditions, index % 3 === 0 ? 'approval=true AND window=maintenance' : 'risk<=medium'), risk: text(row.risk, index < 3 ? 'Critical' : index < 7 ? 'High' : 'Medium'), state: text(row.state, index % 4 === 0 ? 'Draft' : 'Published'), hits: number(row.hit_count, index % 5 === 0 ? 0 : 12 + index * 3), expiry: text(row.expires_at, index % 4 === 0 ? '7d' : 'None'), revision: text(row.revision, `r${14 - index % 4}`), conflict: text(row.conflict, index % 5 === 0 ? 'Unresolved overlap' : 'None') }));

export function P26AgentRuntimeAccessWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const [query, setQuery] = useState(''); const [risk, setRisk] = useState('High and critical'); const [selectedId, setSelectedId] = useState<string | undefined>(undefined); const [subject, setSubject] = useState('fleet:endpoint'); const [capability, setCapability] = useState('execute.response'); const [resource, setResource] = useState('site:prod'); const [enabled, setEnabled] = useState(true); const [conditions, setConditions] = useState('approval=true AND case.severity>=high'); const [publishOpen, setPublishOpen] = useState(false); const [receipt, setReceipt] = useState<string | undefined>(undefined);
  const policies = useMemo(() => buildPolicies(fixture.rows), [fixture.rows]); const visible = useMemo(() => policies.filter((item) => (!query.trim() || `${item.id} ${item.subject} ${item.capability} ${item.resource} ${item.conditions}`.toLowerCase().includes(query.trim().toLowerCase())) && (risk === 'All risk' || (risk === 'High and critical' ? ['High','Critical'].includes(item.risk) : item.risk === risk))), [policies, query, risk]); const selected = visible.find((item) => item.id === selectedId) ?? visible[0] ?? policies[0]; if (!selected) return null;
  const metrics = { grants: policies.filter((item) => item.effect === 'Allow' && ['High','Critical'].includes(item.risk) && item.state === 'Published').length, conflicts: policies.filter((item) => item.conflict !== 'None').length, unused: policies.filter((item) => item.hits === 0).length, expiry: policies.filter((item) => item.expiry !== 'None').length };
  const simulate = () => setReceipt(`Simulation result: DENY for ${subject} → ${capability} on ${resource}; explicit deny and maintenance-window condition are shown in the trace.`);
  const publish = () => { setReceipt(`Publish request queued for ${selected.id}. Running-task impact, approval, audit receipt and authoritative re-evaluation remain pending.`); setPublishOpen(false); };
  return <div className="pageComposition page-p26 differentiatedPage" data-page-specific-composition="P26-effective-access-policy-editor">
    <EuiFlexGroup gutterSize="s" wrap>{[['High-risk grants', metrics.grants],['Conflicting policies', metrics.conflicts],['Unused grants', metrics.unused],['Pending expiry', metrics.expiry]].map(([label, value]) => <EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup><EuiSpacer size="m" />
    {receipt && <><EuiCallOut title="Policy evaluation receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="policy-grid"><EuiFlexGroup alignItems="center"><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event: ChangeEvent) => setQuery(event.target.value)} placeholder="Policy, agent scope, capability, resource or condition" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={risk} onChange={(event: ChangeEvent) => setRisk(event.target.value)} options={['High and critical','All risk','Critical','High','Medium'].map((value) => ({ value, text: value }))} /></EuiFlexItem></EuiFlexGroup><EuiSpacer size="s" /><table><thead><tr><th>Policy</th><th>Subject</th><th>Capability</th><th>Resource</th><th>Effect</th><th>Risk</th><th>Conflict</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><EuiButtonEmpty size="xs" onClick={() => setSelectedId(item.id)}>{item.id}</EuiButtonEmpty><small>{item.revision} · {item.state}</small></td><td>{item.subject}</td><td>{item.capability}</td><td>{item.resource}</td><td><EuiBadge color={item.effect === 'Allow' ? 'warning' : 'danger'}>{item.effect}</EuiBadge></td><td>{item.risk}</td><td>{item.conflict}</td></tr>)}</tbody></table></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="effective-access-explorer"><EuiTitle size="s"><h2>Effective access explorer</h2></EuiTitle><EuiFlexGroup gutterSize="s"><EuiFlexItem><EuiFormRow label="Agent/fleet"><EuiSelect value={subject} onChange={(event: ChangeEvent) => setSubject(event.target.value)} options={['fleet:endpoint','fleet:cloud','agent:agt-001'].map((value) => ({ value, text: value }))} /></EuiFormRow></EuiFlexItem><EuiFlexItem><EuiFormRow label="Capability"><EuiSelect value={capability} onChange={(event: ChangeEvent) => setCapability(event.target.value)} options={['execute.response','query.events','run.script','read.artifact'].map((value) => ({ value, text: value }))} /></EuiFormRow></EuiFlexItem><EuiFlexItem><EuiFormRow label="Resource"><EuiSelect value={resource} onChange={(event: ChangeEvent) => setResource(event.target.value)} options={['site:prod','dataset:security-1','asset:critical'].map((value) => ({ value, text: value }))} /></EuiFormRow></EuiFlexItem></EuiFlexGroup><EuiFormRow label="Conditions"><EuiTextArea value={conditions} onChange={(event: ChangeEvent) => setConditions(event.target.value)} rows={3} /></EuiFormRow><EuiSwitch checked={enabled} onChange={() => setEnabled((value) => !value)} label="Include current draft" /><EuiSpacer size="m" /><EuiButton fill onClick={simulate}>Simulate decision</EuiButton><EuiSpacer size="m" /><EuiCodeBlock language="text" paddingSize="s">1. explicit deny on site:prod → matched
2. allow execute.response when approval=true → condition false
3. default policy → deny
FINAL: DENY · policy-eval-20260721-018</EuiCodeBlock></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="policy-editor-diff-impact"><EuiTitle size="s"><h2>{selected.id} policy editor</h2></EuiTitle><dl><div><dt>Revision</dt><dd>{selected.revision}</dd></div><div><dt>Hits</dt><dd>{selected.hits}</dd></div><div><dt>Expiry</dt><dd>{selected.expiry}</dd></div><div><dt>Conditions</dt><dd>{selected.conditions}</dd></div></dl><div className="policyDiff"><del>{selected.effect} {selected.capability} on {selected.resource}</del><ins>Allow {capability} on {resource} when {conditions}</ins></div><EuiCallOut title="Running-task impact" color="warning">3 running tasks currently rely on the effective decision. Revocation requires recovery planning.</EuiCallOut><EuiSpacer /><EuiButton fill fullWidth onClick={() => setPublishOpen(true)}>Review publish</EuiButton></EuiPanel></EuiFlexItem>
    </EuiFlexGroup>
    {publishOpen && <EuiModal onClose={() => setPublishOpen(false)} aria-labelledby="p26-publish-title"><EuiModalHeader><EuiModalHeaderTitle id="p26-publish-title">Policy publish and task impact</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="High-risk governance" color="warning">Critical capability grants and revocations require approval, conflict resolution and an audit receipt.</EuiCallOut><ul><li>Policy: {selected.id}</li><li>Risk: {selected.risk}</li><li>Conflict: {selected.conflict}</li><li>Running tasks impacted: 3</li><li>Rollback revision: {selected.revision}</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={() => setPublishOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={publish}>Queue publish</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}
