import { useMemo, useState } from 'react';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiPanel, EuiProgress, EuiSelect, EuiSpacer, EuiStat, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';

type Resource = { key: string; id: string; name: string; type: string; lifecycle: string; validation: string; dependency: string; runtime: string; owner: string; revision: string; consumers: number; risk: string };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const number = (value: PrototypeValue | undefined, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const types = ['Data source','Schema','Detection rule','Runtime object','Script','Playbook'];
const buildResources = (rows: PrototypeRow[]): Resource[] => rows.slice(0, 18).map((row, index) => ({ key: `${row.id}:${index}`, id: text(row.resource_id, `RT-${String(index + 1).padStart(4, '0')}`), name: text(row.name, `${types[index % types.length]} ${index + 1}`), type: text(row.resource_type, types[index % types.length]), lifecycle: text(row.lifecycle, ['Published','Draft','Published','Deprecated'][index % 4]), validation: text(row.validation_state, index % 5 === 0 ? 'Invalid' : 'Valid'), dependency: text(row.dependency_health, index % 6 === 0 ? 'Broken' : index % 5 === 0 ? 'At risk' : 'Healthy'), runtime: text(row.runtime_health, index % 7 === 0 ? 'Degraded' : 'Healthy'), owner: text(row.owner, ['Detection engineering','Data platform','Automation','SOC platform'][index % 4]), revision: text(row.revision, `r${20 - index % 5}`), consumers: number(row.consumer_count, 2 + index * 2), risk: text(row.risk, index < 4 ? 'High' : 'Medium') }));

export function P27RuntimeCatalogOverviewWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const [query, setQuery] = useState(''); const [type, setType] = useState('All resource types'); const [status, setStatus] = useState('Attention required'); const [selectedKey, setSelectedKey] = useState<string | undefined>(undefined); const [receipt, setReceipt] = useState<string | undefined>(undefined);
  const resources = useMemo(() => buildResources(fixture.rows), [fixture.rows]); const visible = useMemo(() => resources.filter((item) => (!query.trim() || `${item.id} ${item.name} ${item.type} ${item.owner}`.toLowerCase().includes(query.trim().toLowerCase())) && (type === 'All resource types' || item.type === type) && (status === 'All status' || (status === 'Attention required' ? item.validation !== 'Valid' || item.dependency !== 'Healthy' || item.runtime !== 'Healthy' : item.lifecycle === status))), [query, resources, status, type]); const selected = visible.find((item) => item.key === selectedKey) ?? visible[0] ?? resources[0]; if (!selected) return null;
  const metrics = { published: resources.filter((item) => item.lifecycle === 'Published').length, invalid: resources.filter((item) => item.lifecycle === 'Draft' && item.validation === 'Invalid').length, broken: resources.filter((item) => item.dependency === 'Broken').length, degraded: resources.filter((item) => item.runtime === 'Degraded').length, pending: resources.filter((item) => item.lifecycle === 'Draft' && item.risk === 'High').length };
  const action = (label: string) => setReceipt(`${label} opened for ${selected.id} in prototype mode; effective runtime resource state is unchanged.`);
  return <div className="pageComposition page-p27 differentiatedPage" data-page-specific-composition="P27-runtime-catalog-readiness-dependency">
    <EuiPanel paddingSize="m" hasBorder data-visual-region="runtime-catalog-scope"><EuiFlexGroup gutterSize="s" alignItems="center" wrap><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event: ChangeEvent) => setQuery(event.target.value)} placeholder="Resource ID, name, type, owner or consumer" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={type} onChange={(event: ChangeEvent) => setType(event.target.value)} options={['All resource types', ...types].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={status} onChange={(event: ChangeEvent) => setStatus(event.target.value)} options={['Attention required','All status','Published','Draft','Deprecated'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={() => setReceipt('Create resource selector opened; choose a type-specific editor. No generic resource was created.')}>Create resource</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m" />{receipt && <><EuiCallOut title="Prototype catalog receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiFlexGroup gutterSize="s" wrap>{[['Published resources', metrics.published],['Invalid drafts', metrics.invalid],['Broken dependencies', metrics.broken],['Runtime degraded', metrics.degraded],['Pending governance', metrics.pending]].map(([label, value]) => <EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
    <EuiSpacer size="m" /><EuiFlexGroup className="p27Workspace" gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={3}><EuiPanel paddingSize="m" hasBorder data-visual-region="catalog-readiness-by-type"><EuiTitle size="s"><h2>Readiness by resource type</h2></EuiTitle>{types.map((name, index) => { const ready = 55 + index * 4; const draft = 25 - index; const invalid = 20 - index * 3; return <div className="p27ReadinessRow" key={name}><header><strong>{name}</strong><small>{resources.filter((item) => item.type === name).length} resources</small></header><div className="readinessStack" aria-label={`${name}: ${ready}% ready, ${draft}% draft, ${invalid}% invalid or degraded`}><span style={{ width: `${ready}%` }}>Ready {ready}%</span><i style={{ width: `${draft}%` }}>Draft {draft}%</i><b style={{ width: `${invalid}%` }}>Invalid or degraded {invalid}%</b></div><div className="p27ReadinessLegend" aria-hidden="true"><span>Ready</span><span>Draft</span><span>Invalid</span></div></div>; })}</EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="runtime-attention-table"><EuiTitle size="s"><h2>Runtime attention queue</h2></EuiTitle><div className="p27TableWrap"><table><thead><tr><th>Resource</th><th>Type</th><th>Lifecycle</th><th>Validation</th><th>Dependencies</th><th>Runtime</th><th>Consumers</th></tr></thead><tbody>{visible.map((item) => <tr key={item.key}><td><EuiButtonEmpty size="xs" onClick={() => setSelectedKey(item.key)}>{item.id}</EuiButtonEmpty><small>{item.name}</small></td><td>{item.type}</td><td>{item.lifecycle}</td><td><EuiBadge color={item.validation === 'Valid' ? 'success' : 'danger'}>{item.validation}</EuiBadge></td><td>{item.dependency}</td><td>{item.runtime}</td><td>{item.consumers}</td></tr>)}</tbody></table></div></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="runtime-resource-preview-dependency"><EuiFlexGroup alignItems="center"><EuiFlexItem><EuiTitle size="s"><h2>{selected.name}</h2></EuiTitle><p>{selected.id} · {selected.type} · {selected.revision}</p></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color={selected.dependency === 'Healthy' ? 'success' : 'danger'}>{selected.dependency}</EuiBadge></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m" /><div className="dependencyMap"><span className="center">{selected.id}</span>{['Schema input','Upstream source','Detection consumer','Dashboard consumer','Playbook consumer','Audit ledger'].map((item, index) => <span key={item} className={`node node-${index}`}>{item}<small>{index < 2 ? 'Dependency' : 'Consumer'}</small></span>)}</div><EuiSpacer /><dl><div><dt>Owner</dt><dd>{selected.owner}</dd></div><div><dt>Consumers</dt><dd>{selected.consumers}</dd></div><div><dt>Runtime health</dt><dd>{selected.runtime}</dd></div><div><dt>Validation</dt><dd>{selected.validation}</dd></div></dl><EuiProgress value={selected.dependency === 'Healthy' ? 92 : 38} max={100} size="s" color={selected.dependency === 'Healthy' ? 'primary' : 'warning'} /><EuiSpacer /><EuiFlexGroup gutterSize="s" wrap><EuiFlexItem grow={false}><EuiButton fill onClick={() => action('Open type-specific editor')}>Open editor</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty onClick={() => action('Validate resource')}>Validate</EuiButtonEmpty></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty color="danger" onClick={() => action('Deprecation review')}>Review deprecate</EuiButtonEmpty></EuiFlexItem></EuiFlexGroup></EuiPanel></EuiFlexItem>
    </EuiFlexGroup>
  </div>;
}
