import { useMemo, useState } from 'react';
import { EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiCodeBlock, EuiFieldSearch, EuiFlexGroup, EuiFlexItem, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiPanel, EuiProgress, EuiSelect, EuiSpacer, EuiStat, EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';

type Source = { id: string; name: string; vendor: string; type: string; site: string; health: string; auth: string; rate: number; rejected: number; lag: number; mapping: string; unmapped: number; credential: string; owner: string; consumers: string[] };
type ChangeEvent = { target: { value: string } };
const text = (value: PrototypeValue | undefined, fallback: string) => value === undefined ? fallback : String(value);
const number = (value: PrototypeValue | undefined, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const buildSources = (rows: PrototypeRow[]): Source[] => rows.slice(0, 12).map((row, index) => ({ id: text(row.source_id, `SRC-${String(index + 1).padStart(3, '0')}`), name: text(row.source_name, ['Edge firewalls','Identity gateway','Endpoint telemetry','Cloud audit'][index % 4]), vendor: text(row.vendor, ['Palo Alto','Okta','Elastic Agent','AWS'][index % 4]), type: text(row.source_type, ['Syslog','API','Agent','Cloud'][index % 4]), site: text(row.site, ['Taipei','Global','Endpoint fleet','Cloud'][index % 4]), health: text(row.health, index % 5 === 0 ? 'Auth error' : index % 6 === 0 ? 'Degraded' : 'Healthy'), auth: text(row.credential_state, index % 5 === 0 ? 'Failed' : index % 4 === 0 ? 'Expires in 7d' : 'Valid'), rate: number(row.events_per_minute, 1200 + index * 380), rejected: number(row.rejected_events, index % 4 === 0 ? 214 + index * 7 : index * 3), lag: number(row.watermark_lag_minutes, index % 5 === 0 ? 38 : 2 + index), mapping: text(row.mapping_state, index % 6 === 0 ? 'Errors' : 'Published r12'), unmapped: number(row.unmapped_fields, index % 6 === 0 ? 17 : index % 3), credential: text(row.credential_alias, `secret://connector/${index + 1}`), owner: text(row.owner, ['Network','Identity','Endpoint','Cloud platform'][index % 4]), consumers: ['P07 Event Search', `Rule pack ${index % 4 + 1}`, 'P01 SOC Overview'] }));

export function P28DataSourcesIntegrationsWorkspace({ fixture }: { fixture: PrototypePageFixture }) {
  const [query, setQuery] = useState(''); const [health, setHealth] = useState('Unhealthy first'); const [selectedId, setSelectedId] = useState<string | undefined>(undefined); const [actionOpen, setActionOpen] = useState(false); const [action, setAction] = useState('Test connection'); const [receipt, setReceipt] = useState<string | undefined>(undefined);
  const sources = useMemo(() => buildSources(fixture.rows), [fixture.rows]); const visible = useMemo(() => sources.filter((item) => (!query.trim() || `${item.id} ${item.name} ${item.vendor} ${item.type} ${item.site} ${item.owner}`.toLowerCase().includes(query.trim().toLowerCase())) && (health === 'All health' || (health === 'Unhealthy first' ? item.health !== 'Healthy' : item.health === health))), [health, query, sources]); const selected = visible.find((item) => item.id === selectedId) ?? visible[0] ?? sources[0]; if (!selected) return null;
  const metrics = { healthy: sources.filter((item) => item.health === 'Healthy' && item.auth === 'Valid' && item.lag < 15 && item.mapping.startsWith('Published')).length, unhealthy: sources.filter((item) => item.health !== 'Healthy').length, rejected: sources.reduce((sum, item) => sum + item.rejected, 0), freshness: sources.filter((item) => item.lag >= 15).length, expiry: sources.filter((item) => item.auth.includes('Expires')).length };
  const queue = () => { setReceipt(`${action} queued for ${selected.id}. Connection, credential, mapping and ingest state remain authoritative and will be rehydrated separately.`); setActionOpen(false); };
  return <div className="pageComposition page-p28 differentiatedPage" data-page-specific-composition="P28-source-ingest-mapping-recovery">
    <EuiPanel paddingSize="m" hasBorder data-visual-region="source-scope-bar"><EuiFlexGroup gutterSize="s" alignItems="center" wrap><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(event: ChangeEvent) => setQuery(event.target.value)} placeholder="Source, vendor, endpoint, dataset, schema, site, owner or credential alias" /></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={health} onChange={(event: ChangeEvent) => setHealth(event.target.value)} options={['Unhealthy first','All health','Healthy','Degraded','Auth error'].map((value) => ({ value, text: value }))} /></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={() => { setAction('Add data source'); setActionOpen(true); }}>Add data source</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
    <EuiSpacer size="m" />{receipt && <><EuiCallOut title="Prototype integration receipt" color="warning">{receipt}</EuiCallOut><EuiSpacer size="m" /></>}
    <EuiFlexGroup gutterSize="s" wrap>{[['Healthy sources', metrics.healthy],['Degraded/offline', metrics.unhealthy],['Events rejected 1h', metrics.rejected],['Freshness breaches', metrics.freshness],['Credentials expiring', metrics.expiry]].map(([label, value]) => <EuiFlexItem key={String(label)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(value)} description={label} titleSize="s" /></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
    <EuiSpacer size="m" /><EuiFlexGroup gutterSize="m" alignItems="stretch" responsive={false}>
      <EuiFlexItem grow={5}><EuiPanel paddingSize="m" hasBorder data-visual-region="source-health-grid"><EuiTitle size="s"><h2>Source connection and ingest health</h2></EuiTitle><table><thead><tr><th>Source</th><th>Vendor/type</th><th>Health</th><th>Rate</th><th>Rejected</th><th>Lag</th><th>Mapping</th><th>Credential</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><EuiButtonEmpty size="xs" onClick={() => setSelectedId(item.id)}>{item.id}</EuiButtonEmpty><small>{item.name} · {item.site}</small></td><td>{item.vendor} / {item.type}</td><td><EuiBadge color={item.health === 'Healthy' ? 'success' : item.health === 'Degraded' ? 'warning' : 'danger'}>{item.health}</EuiBadge></td><td>{item.rate}/m</td><td>{item.rejected}</td><td>{item.lag}m</td><td>{item.mapping}</td><td>{item.auth}</td></tr>)}</tbody></table></EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="source-ingest-lag-analysis"><EuiTitle size="s"><h2>Ingest rate and lag</h2></EuiTitle><div className="ingestChart" role="img" aria-label="Accepted events and watermark lag; exact source values follow.">{sources.slice(0, 8).map((item) => <div key={item.id}><span style={{ height: `${Math.min(100, item.rate / 35)}%` }} /><i style={{ height: `${Math.min(100, item.lag * 2)}%` }} /><small>{item.id}</small></div>)}</div><table className="chartFallback"><caption>Exact ingest and lag data</caption><thead><tr><th>Source</th><th>Events/min</th><th>Rejected</th><th>Lag</th></tr></thead><tbody>{sources.slice(0, 8).map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.rate}</td><td>{item.rejected}</td><td>{item.lag}m</td></tr>)}</tbody></table><EuiSpacer /><EuiTitle size="xs"><h3>Rejected by reason</h3></EuiTitle>{[['Authentication',38],['Transport',22],['Schema',54],['Mapping',71]].map(([label, value]) => <div key={String(label)}><strong>{label}</strong><EuiProgress value={Number(value)} max={100} size="s" color={Number(value) > 50 ? 'warning' : 'primary'} /><span>{value}</span></div>)}</EuiPanel></EuiFlexItem>
      <EuiFlexItem grow={4}><EuiPanel paddingSize="m" hasBorder data-visual-region="source-connection-mapping-workbench"><EuiFlexGroup alignItems="center"><EuiFlexItem><EuiTitle size="s"><h2>{selected.name}</h2></EuiTitle><p>{selected.id} · {selected.vendor} · {selected.site}</p></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color={selected.mapping.startsWith('Published') ? 'success' : 'danger'}>{selected.mapping}</EuiBadge></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m" /><dl><div><dt>Credential alias</dt><dd>{selected.credential}</dd></div><div><dt>Connection</dt><dd>{selected.health}</dd></div><div><dt>Watermark lag</dt><dd>{selected.lag}m</dd></div><div><dt>Unmapped fields</dt><dd>{selected.unmapped}</dd></div><div><dt>Owner</dt><dd>{selected.owner}</dd></div></dl><EuiTitle size="xs"><h3>Consumers</h3></EuiTitle>{selected.consumers.map((item) => <EuiBadge key={item} color="hollow">{item}</EuiBadge>)}<EuiSpacer /><EuiCodeBlock language="json" paddingSize="s">{JSON.stringify({ mappingRevision: selected.mapping, unmappedFields: selected.unmapped, sample: { event_category: 'authentication', source_ip: 'masked' } }, null, 2)}</EuiCodeBlock><EuiSpacer /><EuiFlexGroup gutterSize="s" wrap>{['Test connection','Pause source','Rotate credential','Publish mapping'].map((label) => <EuiFlexItem key={label} grow={false}><EuiButtonEmpty color={label === 'Pause source' ? 'danger' : 'primary'} onClick={() => { setAction(label); setActionOpen(true); }}>{label}</EuiButtonEmpty></EuiFlexItem>)}</EuiFlexGroup></EuiPanel></EuiFlexItem>
    </EuiFlexGroup>
    {actionOpen && <EuiModal onClose={() => setActionOpen(false)} aria-labelledby="p28-action-title"><EuiModalHeader><EuiModalHeaderTitle id="p28-action-title">{action} impact review</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="Integration governance" color="warning">Required-source pause, credential rotation and breaking mapping publication require impact review and separate authoritative receipts.</EuiCallOut><ul><li>Source: {selected.id}</li><li>Health: {selected.health}</li><li>Consumers: {selected.consumers.length}</li><li>Current mapping: {selected.mapping}</li><li>Rollback: previous mapping/credential revision retained</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={() => setActionOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={queue}>Queue action</EuiButton></EuiModalFooter></EuiModal>}
  </div>;
}
