import { useMemo, useState } from 'react';
import { EuiBadge,EuiButton,EuiButtonEmpty,EuiCallOut,EuiFieldSearch,EuiFlexGroup,EuiFlexItem,EuiFlyout,EuiFlyoutBody,EuiFlyoutFooter,EuiFlyoutHeader,EuiModal,EuiModalBody,EuiModalFooter,EuiModalHeader,EuiModalHeaderTitle,EuiPanel,EuiSelect,EuiSpacer,EuiStat,EuiTitle } from '@elastic/eui';
import type { PrototypePageFixture, PrototypeRow, PrototypeValue } from '../../types/prototype';
import './P37UsersWorkspace.css';
type User={id:string;name:string;principal:string;provider:string;status:string;mfa:string;roles:string[];sessions:number;lastSignIn:string;manager:string;risk:string;binding:string}; type ChangeEvent={target:{value:string}};
const text=(v:PrototypeValue|undefined,f:string)=>v===undefined?f:String(v);
const build=(rows:PrototypeRow[]):User[]=>rows.slice(0,16).map((r,i)=>({id:text(r.user_id,`USR-${1000+i}`),name:text(r.display_name,['Avery Chen','Mina Patel','Jordan Kim','Riley Lin'][i%4]),principal:text(r.email,`user${i+1}@example.internal`),provider:text(r.provider,['Native','SAML','OIDC','LDAP'][i%4]),status:text(r.status,i%6===0?'Locked':i%5===0?'Disabled':'Active'),mfa:text(r.mfa_state,i%4===0?'Gap':'Compliant'),roles:['soc_analyst',i%3===0?'privileged_response':'case_reader'],sessions:i%5,risk:i%4===0?'High':'Normal',lastSignIn:text(r.last_signin_at,`${i+1}h ago`),manager:text(r.manager,'Security Operations'),binding:text(r.provider_subject,`subject-${i+1}`)}));
export function P37UsersWorkspace({fixture}:{fixture:PrototypePageFixture}){const[query,setQuery]=useState('');const[status,setStatus]=useState('Attention first');const[selectedId,setSelectedId]=useState<string | undefined>(undefined);const[detailOpen,setDetailOpen]=useState(false);const[actionOpen,setActionOpen]=useState(false);const[action,setAction]=useState('Disable user');const[receipt,setReceipt]=useState<string | undefined>(undefined);const users=useMemo(()=>build(fixture.rows),[fixture.rows]);const visible=useMemo(()=>users.filter(u=>(!query.trim()||`${u.id} ${u.name} ${u.principal} ${u.provider} ${u.roles.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(status==='All status'||(status==='Attention first'?u.status!=='Active'||u.mfa==='Gap'||u.risk==='High':u.status===status))),[query,status,users]);const selected=visible.find(u=>u.id===selectedId)??visible[0]??users[0];if(!selected)return null;const metrics={active:users.filter(u=>u.status==='Active').length,locked:users.filter(u=>u.status!=='Active').length,mfa:users.filter(u=>u.mfa==='Gap').length,dormant:users.filter((_,i)=>i%5===0).length,sessions:users.filter(u=>u.sessions>2).length};const queue=()=>{setReceipt(`${action} queued for ${selected.id}. Identity, role, MFA and session services remain authoritative.`);setActionOpen(false)};return <div className="pageComposition differentiatedPage p37Users" data-page-specific-composition="P37-user-governance-detail-security">
<EuiPanel paddingSize="m" hasBorder><EuiFlexGroup gutterSize="m" alignItems="center" wrap><EuiFlexItem grow={2}><EuiFieldSearch compressed value={query} onChange={(e:ChangeEvent)=>setQuery(e.target.value)} placeholder="User ID, name, principal, provider, role or scope"/></EuiFlexItem><EuiFlexItem grow={false}><EuiSelect compressed value={status} onChange={(e:ChangeEvent)=>setStatus(e.target.value)} options={['Attention first','All status','Active','Locked','Disabled'].map(v=>({value:v,text:v}))}/></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color="hollow">Directory fresh 3m</EuiBadge></EuiFlexItem><EuiFlexItem grow={false}><EuiButton fill onClick={()=>setReceipt('Invite user wizard opened in prototype mode.')}>Invite user</EuiButton></EuiFlexItem></EuiFlexGroup></EuiPanel>
{receipt&&<EuiCallOut title="Prototype identity receipt" color="warning">{receipt}</EuiCallOut>}
<EuiFlexGroup gutterSize="m" wrap className="p37Stats">{[['Active users',metrics.active],['Locked / disabled',metrics.locked],['MFA gaps',metrics.mfa],['Dormant privileged',metrics.dormant],['Sessions at risk',metrics.sessions]].map(([l,v])=><EuiFlexItem key={String(l)}><EuiPanel paddingSize="s" hasBorder><EuiStat title={String(v)} description={l} titleSize="s"/></EuiPanel></EuiFlexItem>)}</EuiFlexGroup>
<div className="p37Layout"><EuiPanel paddingSize="m" hasBorder className="p37Table"><EuiTitle size="s"><h2>User governance</h2></EuiTitle><div className="p37TableWrap"><table><thead><tr><th>User</th><th>Provider</th><th>Status</th><th>MFA</th><th>Roles</th><th>Sessions</th><th>Last sign-in</th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><EuiButtonEmpty size="xs" onClick={()=>setSelectedId(u.id)}>{u.name}</EuiButtonEmpty><small>{u.id} · {u.principal}</small></td><td>{u.provider}<small>{u.binding}</small></td><td><EuiBadge color={u.status==='Active'?'success':'danger'}>{u.status}</EuiBadge></td><td><EuiBadge color={u.mfa==='Compliant'?'success':'warning'}>{u.mfa}</EuiBadge></td><td>{u.roles.join(', ')}</td><td>{u.sessions}</td><td>{u.lastSignIn}</td></tr>)}</tbody></table></div></EuiPanel>
<EuiPanel paddingSize="m" hasBorder className="p37Detail"><EuiFlexGroup alignItems="center" wrap><EuiFlexItem><EuiTitle size="s"><h2>{selected.name}</h2></EuiTitle><p>{selected.id} · {selected.principal}</p></EuiFlexItem><EuiFlexItem grow={false}><EuiBadge color={selected.risk==='High'?'danger':'success'}>{selected.risk} risk</EuiBadge></EuiFlexItem></EuiFlexGroup><EuiSpacer size="m"/><dl><div><dt>Identity source</dt><dd>{selected.provider} / {selected.binding}</dd></div><div><dt>Manager</dt><dd>{selected.manager}</dd></div><div><dt>Effective roles</dt><dd>{selected.roles.join(', ')}</dd></div><div><dt>Active sessions</dt><dd>{selected.sessions}</dd></div></dl><EuiCallOut title="Effective access">Direct and group roles are combined; privileged capabilities require separate review.</EuiCallOut><EuiSpacer size="m"/><EuiFlexGroup gutterSize="s" wrap><EuiFlexItem grow={false}><EuiButton onClick={()=>setDetailOpen(true)}>Sessions & activity</EuiButton></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty onClick={()=>{setAction('Reset MFA');setActionOpen(true)}}>Reset MFA</EuiButtonEmpty></EuiFlexItem><EuiFlexItem grow={false}><EuiButtonEmpty color="danger" onClick={()=>{setAction('Disable user');setActionOpen(true)}}>Disable</EuiButtonEmpty></EuiFlexItem></EuiFlexGroup></EuiPanel>
<EuiPanel paddingSize="m" hasBorder className="p37Security"><EuiTitle size="s"><h2>Lifecycle & security</h2></EuiTitle>{[['Provider consistency',selected.status==='Active'?'Aligned':'Review'],['MFA policy',selected.mfa],['Session risk',selected.sessions>2?'Elevated':'Normal'],['Privileged role',selected.roles.some(r=>r.includes('privileged'))?'Present':'None']].map(([l,v])=><div key={l}><strong>{l}</strong><EuiBadge color={/Review|Gap|Elevated|Present/.test(v)?'warning':'success'}>{v}</EuiBadge></div>)}</EuiPanel></div>
{detailOpen&&<EuiFlyout onClose={()=>setDetailOpen(false)} ownFocus size="m" aria-labelledby="p37-detail-title"><EuiFlyoutHeader><EuiTitle><h2 id="p37-detail-title">Sessions, activity and ownership</h2></EuiTitle></EuiFlyoutHeader><EuiFlyoutBody>{fixture.timeline.slice(0,8).map((t,i)=><article key={`${t.time}-${i}`}><strong>{t.title}</strong><span>{t.time}</span><p>{t.detail}</p></article>)}</EuiFlyoutBody><EuiFlyoutFooter><EuiButton onClick={()=>setDetailOpen(false)}>Close</EuiButton></EuiFlyoutFooter></EuiFlyout>}
{actionOpen&&<EuiModal onClose={()=>setActionOpen(false)} aria-labelledby="p37-action-title"><EuiModalHeader><EuiModalHeaderTitle id="p37-action-title">{action} impact review</EuiModalHeaderTitle></EuiModalHeader><EuiModalBody><EuiCallOut title="High-risk identity action" color="warning">Sessions, ownership, break-glass coverage and effective access must be reviewed before execution.</EuiCallOut><ul><li>User: {selected.id}</li><li>Sessions: {selected.sessions}</li><li>Roles: {selected.roles.join(', ')}</li></ul></EuiModalBody><EuiModalFooter><EuiButtonEmpty onClick={()=>setActionOpen(false)}>Cancel</EuiButtonEmpty><EuiButton fill onClick={queue}>Queue action</EuiButton></EuiModalFooter></EuiModal>}</div>}
